### ISSUE TITLE
Damages in Gelatinous Cube Engulf do not parse in 

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#1010]
https://www.dndbeyond.com/monsters/16869-gelatinous-cube

![image](https://user-images.githubusercontent.com/7988297/183274008-c2e78285-1552-4767-b98f-6ccbdadeb3e6.png)

**Comment by kakaroto** [comment]
Ha, found the bug. It was affecting not just Gelatinous Cube. See Beholder : 
![image](https://user-images.githubusercontent.com/27990/183296951-6cdbe4ff-7ed6-4e41-bdd1-285a29e5710c.png)

**Comment by Aeristoka** [comment]
Did they change formatting or something?

**Comment by kakaroto** [comment]
> Did they change formatting or something?

nope, always a bug in the code I think.
For beholder, it's a list (`<ol><li>...</li><li>...</li></ol>`) and we don't even look for that, we only search for `<p>` tags.
For the Engulf, it might be because they added a span around the damage to define the type of damage, but still, looks like the code would only take the very first paragraph as part of the action.
This is the code that fails : https://github.com/kakaroto/Beyond20/blob/master/src/dndbeyond/base/monster.js#L515
It checks "oh, it's not an action, let's inject dice rolls and continue", and then 2 lines later, there are two other checks which do `continue` without doing the same "replace dice" code. So that's our bug.

This is my fix, but as you can see, it's not complete : 
![image](https://user-images.githubusercontent.com/27990/183297537-0754946d-1628-45a7-81c5-993158f73b57.png)

While the dice formulas are replaced, the engulf action itself doesn't include that damage, and the description doesn't include the other paragraphs that should be part of the same action. I think some refactoring is needed here to make it work
