### ISSUE TITLE
Zealot Barbarian's Divine Fury should only apply to the next attack.

### ISSUE THREAD

**Issue by MistressAshai** [kakaroto/Beyond20#1019]
Zealot Barbarian's Divine Fury option should function like the Great Weapon Master feat and turn off after the next attack.
Constantly having to toggle it on and off in Beyond20's settings is a real pain.

**Comment by kakaroto** [comment]
> Starting when you choose this path at 3rd level, you can channel divine fury into your weapon strikes. While you’re raging, the first creature you hit on each of your turns with a weapon attack takes extra damage equal to 1d6 + half your barbarian level. The extra damage is necrotic or radiant; you choose the type of damage when you gain this feature.

As per the description, it's an extra damage that automatically applies on each of your turns. It is similar to Sneak Attack, which is why it doesn't disable after attack. The damages are separated and clearly labeled so you can decide whether it applies or not. 
Great Weapon Master functions differently in that it is a **choice** that you have to make (which imposes a penalty). Any other feature which we disable after an attack will also be something very specific where you need to make a choice or that are limited in how often you can do it, (like Divine Smite, which would use one of your spell slots).
In this case, as it applies automatically on each of your turns, it remains enabled, like Sneak Attack.

Changing its behavior will cause anyone depending on it to complain that it's a real pain to have to enable the option on each turn. It's much easier to roll your attacks and say that the Divine Fury damage doesn't apply because it's your second attack, rather than having to re-enable it every time, or forgetting that the class feature exists or having to roll it separately because you forgot to enable it. 
Reminder that this is a TTRPG, not a video game, and making decisions and verbally announcing them to the DM and doing simple math generally goes a long way to making it a smooth play.

Also note that alternatively, you can also just keep the option disabled and instead set up a custom hotkey which would only enable it while you roll while having that hotkey pressed. In your situation, it'd likely be the much easier solution.
I hope that helps.

**Comment by Wyrmwood** [comment]
1st - 4th level without polearm master or two weapon fighting or any other secondary attack is the only time this argument makes sense to me. PotZ should be next attack only and GWM should toggle. Seems backward to me. Nice tool, though.

**Comment by MistressAshai** [comment]
Yeah, honestly I still disagree on how having to slow the game down to go "oh wait that didn't apply to all my attacks so subtract it from the other 4 attacks" is somehow "smooth play". I can also understand how people would complain about it. I would suggest displaying total damage both with and without these [first attack] effects.

**Comment by kakaroto** [comment]
Like I said, if you want to disable it, then disable it and use a hotkey to temporarily enable it only while pressed. It would still be much smoother for you to press a hotkey like Z while you click your first attack, then having to go in the menu to enable it before each attack.
You have every right to disagree with the decision, but I am quite certain that having it be a single use toggle would be completely backwards and extremely annoying to the other half a miliion users of the extension. 
The idea that you think GWM should itself be a toggle baffles me.

**Comment by MistressAshai** [comment]
Not talking about toggles. This could be made more clear in the roll results without the need for user input. Extra attacks exist and are what make this an issue in the first place.

Something like this would improve readability:
![image](https://user-images.githubusercontent.com/8222603/228094971-64f38d37-9b8b-4586-ba6c-477ccfdd92da.png)
