### ISSUE TITLE
Permission to view browsing history?

### ISSUE THREAD

**Issue by HeleniusTG** [kakaroto/Beyond20#1031]
Not really a feature request, but this is the only place I could find where I could ask a question directly.

The tool from what I have tested works great, fantastic little bit of code. Good work!

However, can someone please explain to me why the roll 20 chrome extension needs the permission to 'view browsing history'? It seems irrelevant to the intended purpose of the tool and sends up a bit of a red flag in my mind.

**Comment by kakaroto** [comment]
Hi!
I'm glad you like the extension and I hope you find it useful in your games!

The extension doesn't "read browsing history", however it requires the "tabs" permission which allows the extension from the DDB tab to send messages to the roll20 tab. That permission is displayed in Chrome as the ability to view your browsing history, because theoretically, if we can find your roll20 tab to send the roll message to it, we could also find all your other tabs and see what site they are on, which is equivalent to monitoring your browsing. That's why Chrome displays the "tabs" permission as being the ability to read browsing history.
The extension however only uses that permission to send messages from one tab to another (from DDB to Roll20 or Foundry)
I hope that answers your question!

If you want to join us on Discord, you can do so from here : https://discord.gg/ZAasSVS
That'd be the best place to engage with the community and get responses quickly to your questions.
Thanks!
