### ISSUE TITLE
Apply custom modifiers on Extra creatures of type wildshape

### ISSUE THREAD

**Issue by BattleMetalChris** [kakaroto/Beyond20#1058]
**Is your feature request related to a problem? Please describe.**
I play a druid, and use the dndbeyond monster pages for the wildshape. This is great, as the beyond20 integration lets me click on there and it sends it to roll20.

However, I now have a magic item that adds a modifier to my wildshape attacks and I can't see how to add it.
I can add modifiers to the rolls from my character sheet, but not from the dndbeyond monster pages

**Describe the solution you'd like**
A way to add dice modifiers to clicks that aren't on the character sheet

**Describe alternatives you've considered**
None really, short of just saying 'this needs a 2 added to it' when I roll

**Additional context**
To clarify, I mean when I click on the dice rolls on pages like this: https://imgur.com/kYpXsyO

**Comment by BattleMetalChris** [comment]
Tried it out in my game today, and couldn't get any modifiers to apply to the Wildshape attacks

**Comment by kakaroto** [comment]
> Tried it out in my game today, and couldn't get any modifiers to apply to the Wildshape attacks, even when they're added to the Extras in dndbeyond

Which is why I didn't close this issue, but instead renamed it and said that I found a bug where it's actually not applying the custom modifiers.
However,  I was hoping the to-hit values would have been automatically adjusted in the statblock because D&D Beyond will sometimes do that when you have magic items or other stuff that can affect the stats of a wildshape/beast companion.

**Comment by BattleMetalChris** [comment]
I'm guessing that because it's an issue with dndbeyond itself and not just translating that to roll20, that there's not a lot that can be done unless WoTC fix the issue at their end?

**Comment by kakaroto** [comment]
Ideally yeah, but I'll add support for the custom modifers in the next release. In the meantime, I'd recommend you set up a hotkey to use with wildshape.

Click the Beyond20 button next to the character name, then `More Options`,  then "Set Hotkeys"
![image](https://user-images.githubusercontent.com/27990/229927921-0b2a0f87-4d77-4cce-950f-e54377845fcb.png)
Add a new hotkey (like `w` key for wildshape if you want), and set it to use a custom modifier:
![image](https://user-images.githubusercontent.com/27990/229928010-e5008c7f-b65d-4efc-9745-8ccff3122865.png)

It should then work if you press the hotkey while you make your rolls while in wildshape. It's not the most practical since you need to remember to press the key every time you roll, but it should work.
