### ISSUE TITLE
Hunter's Mark MIA? Sheet scan incomplete? Or just user over-expectations?

### ISSUE THREAD

**Issue by jh4c** [kakaroto/Beyond20#1092]
Due to a quirk of the campaign I'm currently in, I've been playing using DDB and B20 for a few months now without having to use (/be able to use in the setting) Hunter's Mark. However, in out last session the restriction was lifted for a battle ... and I couldn't find where to enable it. I was expecting a toggle like the one I have for favored Foe, so that it would auto-roll every time I make a hit, but the only place it shows is in the spell itself.

I've looked all through the basic options when looking at the DDB page for my character, and also the Advanced ones. I've looked at the B20 options when not on any website. I've looked at them when on Roll20 (the VTT we're using) just in case. Nothing found anywhere. I did a web search, which led me here to two comments, one an older issue about the roll for HM being performed 3 times, and another stating that this bug had been fixed a couple of years back - so at least I've now found evidence that this is, or at least was, a supported function. I've checked old notes and can't find anything saying it's been removed so... Where's it gone? I even made a throwaway in case the fact I'm using optional rules has caused a conflict, sticking solely to the handbook for a character of equivalent level, and no joy.

**To Reproduce**
1. Go to DDB
2. Make/load a Ranger of any kind that knows the first level spell Hunter's Mark (available at charater level 2), switching panels as advised by B20 to alert it to your spells
3. Open the Beyond20 panel to see the options available to your character.
4. Note an absence of Hunter's Mark

**Expected behavior**
I will note that when I first loaded B20, when it detected a new or levelled character and told me to flip the pages of my character's profile so it could parse my skills, I seem to recall it gave a second pop-up saying that it had done this successfully - this has not happened with my test characters, but reloading the DDB page no longer gives the pop-up to perform the scan either, so I have to assume it completed.
 
**Screenshots**
First, the B20 panel overlaying my available spells, showing I have Hunter's Mark but no toggle to add it to my regular damage roll; second, the one spot I have a specific B20 "cast" button for it which is so hidden away it makes it less convenient than just using the default button from DDB.
  
**Browser Info (please complete the following information):**
 - Firefox 119.0.1 (up to date)
 - the only console errors I seem to be getting are from DDB's dice rendering routine being outdated or something - it's all webgl rendering stuff; that said, this is shown in the events list but the pop-up didn't appear.
`Received response :  
Object { success: false, vtt: null, request: {…}, error: "No VTT found that matches your settings. Open a VTT window, or check that the settings don't restrict access to a specific campaign." }
[dndbeyond_character.js:4971:13]`
 
I hope that's enough to be getting on with, or at least for you to tell that whatever I'm on about doesn't exist in the first place and I'm being a twit. If I am being a twit, I apologise profusely.

**Comment by kakaroto** [comment]
Hi,
Thanks for the detailed report.
I've checked the code and everything and there's never been any specific support for the hunter's mark spell being added as a character option. There's "Hunter's Prey" which is a class feature for Ranger, but we don't have any character-specific options that are spell related. All character specific options are related to class features or racial traits, etc.. not related to available spells.

I've found the other issues you mentioned and they relate to actually rolling/casting the spell itself, not about any kind of automated rolls as part of a character option.
I think if you want to use hunter's mark, you can either roll the spell every time you judge that its damage needs to apply, or you could add a custom damage `Hunter's mark: 1d6` to be added to all attacks after you cast it, same as with those using `Hex: 1d6` custom damage (can also assign the custom damage to a hotkey, which is likely the preferred method).

As for your expected behavior, yeah, I'd also expected the notification that it successfully parsed the sheet, and if it doesn't prompt you on a refresh, it means that it did parse it successfully. I don't see any attached screenshots though so I'm not sure what you're referring to with regards to a cast button being hard to use.

I hope that helps.

**Comment by jh4c** [comment]
Thanks. Not sure what happened to the screenshots, and I deleted them locally... Not important in the big scheme of things. I'll play with adding the damage roll as you've suggested, thanks again for taking the time to answer.
