### ISSUE TITLE
Third whisper setting, where d20 roll is public, but the rest is only to the GM.

### ISSUE THREAD

**Issue by Wyrmwood** [kakaroto/Beyond20#1098]
There are many features in D&D where players have the opportunity to react, after knowing the roll (the actual die roll) but before knowing the outcome. For example, Cutting Words, Silvery Barbs, the Lucky Feat, Divination Wizard's Portent and many others. 

The current whisper setting is all or none, and if you roll attack and damage at the same time, that's quite a bit of information to influence the decision for these types of abilities. 

What would be really nice would be if there was a third option, to have the d20 roll of an attack, ability check or saving throw always display (just the actual die roll, no modifiers), but the rest be whispered to the GM.

**Comment by kakaroto** [comment]
> There are many features in D&D where players have the opportunity to react, after knowing the roll (the actual die roll) but before knowing the outcome. For example, Cutting Words, Silvery Barbs, the Lucky Feat, Divination Wizard's Portent and many others.
> 
> The current whisper setting is all or none, and if you roll attack and damage at the same time, that's quite a bit of information to influence the decision for these types of abilities.
> 
> What would be really nice would be if there was a third option, to have the d20 roll of an attack, ability check or saving throw always display (just the actual die roll, no modifiers), but the rest be whispered to the GM.

In those kinds of cases, the user can just roll the attack without rolling the damages at the same time. Beyond20 has an option for auto-roll damages, and if you use DDB's digital dice, there are roll buttons under both the 'to hit' and 'damage' columns, which serve as rolling only the attack or only the damage, instead of rolling both at once.
As for saving throws/skill checks, you already know your own modifiers for your abilities, so not including the modifiers in the roll has zero advantages other than making you do one math equation in your head.
