### ISSUE TITLE
Super advantage dice roll does not work with hotkey

### ISSUE THREAD

**Issue by shad2810** [kakaroto/Beyond20#1108]
**Describe the bug**
After the current update of V2.9.2, the hotkey does not work for super advantage to roll into roll20 without selecting "Use D&D Beyond's Digital Dice"

**To Reproduce**
![image_2024-04-25_195551916](https://github.com/kakaroto/Beyond20/assets/42043878/05c903e9-e808-4fc5-915b-ec0d80bf0e57)
![image_2024-04-25_195616426](https://github.com/kakaroto/Beyond20/assets/42043878/12082b50-806d-41a1-9dd4-d197a2d59469)
As displayed it does not show 3d20 but 2d20 (Akin to a regular advantage instead) unless you enable "Use D&D Beyond's Digital Dice" before hand which slows down roll when rolling a lot

**Expected behavior**
Should show a 3d20 instead of 2d20

**Screenshots**
Attach is as above

**Browser Info (please complete the following information):**
 - Browser - Opera GX
 - Version - Beyond 20 V2.9.2
 
**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.
No other problems, only that :)

**Comment by jtbg** [comment]
Good news is it looks like the roll is correct - the roll is correct, just displayed incorrectly.

It's sending as  ``` `1d20` | `2d20kh1` ```. Three d20s are rolled, but only two are shown

**Comment by kakaroto** [comment]
As @jtbg said (thanks!) it does roll 3 dice, and if you hover on them, you'll see it. It's a limitation of Roll20 because it does not support displaying 3 dice rolls, only 2, so we had to get creative and roll it in that way. If you enable 3d dice in roll20, you'll probably see all 3 rolled as well.
Closing as invalid, feel free to re-open the issue if you think we misunderstood the situation or you have additional information.
