### ISSUE TITLE
Question regarding future integration with Roll20 native in Discord 

### ISSUE THREAD

**Issue by evie-and-eevees** [kakaroto/Beyond20#1113]
As a paid DM, the vast majority of my players rely on Beyond20 for sending their rolls from D&D Beyond to Roll20. While it won't be a major issue as all my players keep their characters in D&D Beyond campaigns I own, so I'll still be able to view their rolls, I'm wondering if the integration will still work? I do understand that this is a recent announcement, so devs might not have access to the code to be able to see what is possible, but wanted to ask so I can try to plan accordingly for the future. Amazing work on this by the way!

**Comment by kakaroto** [comment]
Hi,
I was a little confused by your message, until I read the title of the issue which is the only place you mention the new Discord activity from Roll20. :)
If you're asking whether Beyond20 will support it because some of your players may want to play through it, then the answer is likely to be yes. A roll20 developer just sent us a pull request which adds support for their Discord activity: https://github.com/kakaroto/Beyond20/pull/1109
I haven't yet had time to review that code and merge it, but I expect it will be supported for the next release, yes.
I hope that answers your question. If it does, please close the issue, otherwise, comment with a follow up :)
