### ISSUE TITLE
Add rollable functionality to Extras section of dndbeyond character sheet

### ISSUE THREAD

**Issue by lplayer12893** [kakaroto/Beyond20#1117]
**Is your feature request related to a problem? Please describe.**
A player who has summoned a creature, wildshaped into a beast, or otherwise has a monster under their control adds that monster to their character sheet via the Extras section in dndbeyond. However, currently they are unable to roll any dice from that monster stat block. If it is an unaltered monster, they can open the full monster stat block and roll from there. However, if it is a wildshape or its stats scale with the player, that is not an option.

I hypothesize that it should be relatively straight forward to apply similar regex parsing and button injecting as is already used on monster stat blocks into those monster stat blocks added in the Extras section. The same should hold true for vehicles added to Extras as well.

**Comment by kakaroto** [comment]
That should already be the case. My guess is that you're probably using Firefox and the 2.9.1 release of Beyond20 which stopped working since last week when D&D Beyond updated their character sheet and broke the parsing of the page by Beyond20.
The 2.9.2 release of Beyond20 is available in the Firefox store, so make sure you update it and try again.
Feel free to re-open the issue if this doesn't solve it for you, providing more information (a character sheet link, a screenshot, etc..) since I don't see any issues with rolling from extra creatures at the moment.
