### ISSUE TITLE
The "Beyond20*" events of the DOM API appear to not be triggered on DnD Beyond itself

### ISSUE THREAD

**Issue by carrierfry** [kakaroto/Beyond20#1130]
**Describe the bug**
The `Beyond20*` events (like `Beyond20_Loaded(settings)`) do not get triggered when on DnD Beyond

**To Reproduce**
1. Create extension or userscript for DnD Beyond character sheet with following code and enable/load it:
```js
function addBeyond20EventListener(name, callback) {
    const event = ["Beyond20_" + name, (evt) => {
        const detail = evt.detail || [];
        callback(...detail)
    }, false];
    document.addEventListener(...event);
    return event;
}

addBeyond20EventListener("Loaded", settings => {
    console.log("Beyond20_Loaded");
    console.log(settings);
});

console.log("Added event listener");
```
2. Open character sheet on DnD Beyond
3. Open DevTools
4. See missing console logs

**Expected behavior**
The `Beyond20*` events should work even on DnD Beyond itself to make 3rd party extensions be able to listen to those events there

**Screenshots**
![image](https://github.com/kakaroto/Beyond20/assets/20256939/271a6098-8c77-4054-895f-933abb69793c)

**Browser Info (please complete the following information):**
 - Browser Google Chrome
 - Version 125.0.6422.141

**Comment by kakaroto** [comment]
While implementing this I realized that it was already implemented as part of https://github.com/kakaroto/Beyond20/issues/833
You can see it in the commit: https://github.com/kakaroto/Beyond20/commit/54037c7065861140c764019a92888b650973e766
The issue however is that it's sending the requests as is using the action name as the event's name instead of the names described in the API documentation (i.e: `Beyond20_hp-update" instead of "Beyond20_UpdateHP" and "Beyond20_roll" instead of "Beyond20_Roll").

I've now fixed it to be consistent with the documented DOM API.
