### ISSUE TITLE
Broken Rolls

### ISSUE THREAD

**Issue by SinifulSerenity2012** [kakaroto/Beyond20#1132]
Hello, 

For some reason when we try to roll melee attacks it will not roll, instead it just shows the describtions. Custom items damage also does not seem to work.

**Comment by dmportella** [comment]
duplicate probably see -> https://github.com/kakaroto/Beyond20/issues/1131

**Comment by smnc** [comment]
**Describe the bug**
Weapon attack rolls and damage rolls do not show up in Roll20

**To Reproduce**
Steps to reproduce the behavior:
1. Open a DDB character sheet.
2. Roll a weapon attack roll, damage roll, or combination roll
3. Rolls will be added to DDB log but will not appear in Roll20, instead the weapon description is sent.

**Expected behavior**
Weapon rolls should appear in Roll20 

**Screenshots**
![image](https://github.com/kakaroto/Beyond20/assets/19196582/7c8e6258-b8ed-418e-b43b-2f6b29fe7e80)

**Browser Info (please complete the following information):**
 - Browser FireFox
 - Version 115.11esr (64bit)
![image](https://github.com/kakaroto/Beyond20/assets/19196582/cff790a3-a139-43fd-942a-47412940c17a)

**Additional context**
Spell attack rolls and damage rolls work as expected - except AOE spells (see #1131)
