### ISSUE TITLE
DnD Beyond can't roll saving throws

### ISSUE THREAD

**Issue by Kodokbotak** [kakaroto/Beyond20#1140]
I don't know if it's just me but whenever i try to roll saving throws, it just wont show up but when i try to roll other checks after attempting to roll a saving throw, it would give me double the check rolls (or attack rolls) but still cant roll saving throws.

**Comment by stonesteel25** [comment]
Can confirm. attack rolls work, but saving throw or ability check rolls (not the skills but the stat rolls) don't.

**Comment by AllenAlonso** [comment]
Unarmed strikes are also not working

**Comment by cherry06716** [comment]
Base ability check rolls and saving throws still arent working.  This is affecting the Jack of all Trades feature since DnD Beyond users rely on Beyond20 to add the half proficiency on base ability check rolls.  DnD Beyond by default only adds Jack of all Trades to Skill and Initiative rolls.

**Comment by x2f01101011** [comment]
Spells and attacks seem to be working, but not saving throws and perhaps subclass features (channel divinity that deals damage)

**Comment by Kodokbotak** [comment]
Also the button that says "Display in VTT" has disappeared from some features

**Comment by kakaroto** [comment]
Hey everyone, thanks for reporting this.

D&D Beyond has updated their character sheet again today, breaking Beyond20 support (as well as breaking many things in the sheet itself for normal DDB user interactions).
I'm trying to get them to realize that this is untenable, because they break the site every week, and it takes more time than that, just to push an update of the extension, so it's chasing our tails infinitely, with users being affected and with no solution in sight.
This is extremely frustrating. I am aware of the issues and I'll tackle them as soon as possible.

Please don't post here just to say "I have the same issue". I understand that **everybody** has the same issues, and I am already quite aware of them.
If you wish to say "me too" without spamming everybody, feel free to use a 👍 reaction on the original issue instead.
Also, if someone wants to try and get a fix and send me a PR for it, I'd much appreciate it.

Thanks for your understanding.

**Comment by Kodokbotak** [comment]
understandable and i thank you for your hard work, i know this is frustrating. What i am afraid of is this will continue until they've released the new 2024 core rulebooks and it's gonna break much more

**Comment by dmportella** [comment]
debugging things i think they renamed the side bar ct-sidebar__portal now

![image](https://github.com/kakaroto/Beyond20/assets/676817/e5285955-538a-4650-baca-98277411472e)

`const pane_name = $(".ct-ability-saving-throws-pane .ct-sidebar__heading").text().slice(0, 3).toLowerCase();`

![image](https://github.com/kakaroto/Beyond20/assets/676817/305846c3-7603-48c7-97b8-5b1c5ce20033)

Running this works

$(".ct-sidebar__portal .ct-sidebar__heading").text().slice(0, 3).toLowerCase();

I will make a dev version see if it works

**Comment by dmportella** [comment]
I have a fix but it is not a nice fix

I added the missing class names to the parent of `.ct-sidebar__header` 

![image](https://github.com/kakaroto/Beyond20/assets/676817/dc55101b-2cd0-435d-b8b8-ca1c458fc7ea)

Also the line of code for the selection of the modifier is falling because of styled components too

changing to `let modifier = $(`.${paneClass}__modifier .ct-signed-number,.${paneClass}__modifier .ddbc-signed-number, span[class*='styles_modifier'] span[class*='styles_numberDisplay']`).text();`

Adding `span[class*='styles_modifier']`

![image](https://github.com/kakaroto/Beyond20/assets/676817/b6c36197-315e-4f79-82b5-93cea1e4199c)

**Comment by Kodokbotak** [comment]
Weird now it's returned to normal, seems like it's been fixed?

**Comment by Nofton** [comment]
> Weird now it's returned to normal, seems like it's been fixed?

This is likely a temporary fix. Per the DDB discord, they rolled back changes because it was breaking/blocking access to some character sheets.

**Comment by kakaroto** [comment]
They haven't rebroken it yet, so I'll close this issue until such tike they break their site again.
Thank you all!

**Comment by dmportella** [comment]
Saving throws and Ability checks are broken because they removed the class from the side panel div

**Comment by StephaniePLee** [comment]
Definitely seems to be doing it again
