### ISSUE TITLE
Chrome not recognizing DnDBeyond as a DnDBeyond page

### ISSUE THREAD

**Issue by Eagle-Man** [kakaroto/Beyond20#1151]
**Describe the bug**
Rolls from DnDBeyond are not being sent to Roll20.  Clicking on the Beyond20 Extension icon shows the "Not a D&D Beyond or VTT page" message.

**To Reproduce**
1. Go to DnDBeyond character sheet.  I have tried several. (eg: https://www.dndbeyond.com/characters/#########)
2. Open Roll20 campaign in another window
3a. Click on Beyond20 extension icon to see message that it's NOT a D&D Beyond page.
3b. Open Developer Console to see JS errors (see images below)
4. Click any button that will roll a die in DnDBeyond.  Die rolls, nothing shows up in Roll20 log.

**Expected behavior**
Roll should be sent to Roll20 window.

**Screenshots**
On load:
![image](https://github.com/user-attachments/assets/cc3e79f5-ba45-48f4-903b-ba92dd882b82)

In extension:
![image](https://github.com/user-attachments/assets/696af417-287f-4c06-bf41-6ea9ca9d1db9)

On roll:
![image](https://github.com/user-attachments/assets/ee3824e2-d845-4a5b-b1d9-1f3b8af3e0a0)

This doesn't appear with every roll, but might be relevant:
![image](https://github.com/user-attachments/assets/c97d98ac-ec62-4b62-9d0f-0718cfcc83de)

**Browser Info (please complete the following information):**
 - Browser: Chrome
 - Version: 109.0.5414.120
 - Windows 7
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT
```
112267193:44          GET https://cdn.gsght.com/sdk.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ 112267193:44
(anonymous) @ 112267193:45
```

**Additional context**
Yes, this is an old OS and it no longer receives Chrome updates - could this be an issue with an incompatibility with the old Chrome version?

**Comment by kakaroto** [comment]
I don't really know why it would do that.. it wouldn't make sense. Since you say you tried several sheets, I wonder if something got corrupted in your install. Can you try to uninstall the extension and reinstall it and see if it works? Also, the errors  I see in your console might be coming from chrome extensions, so I don't know if some extension is somehow interfering, I'm not sure.
As for your chrome version, I don't think it would cause any issues, there's nothing particularly "new" in what Beyond20 uses, and I tend to keep away from newer methods and all that, so I assume that's not it. One thing you can do for example is to right click on the pop up dialog itself and click "Inspect", that will give you the console for the popup dialog itself and maybe there's some clue there as to what's happening for you.
![image](https://github.com/user-attachments/assets/fed780db-9113-4c64-a493-808e57d5a8a3)

Good luck.

**Comment by Eagle-Man** [comment]
Thanks for the reply.  I have been away and didn't get a chance to test out uninstalling and reinstalling, but the newest version has since installed and it seems to be working again.  So I would assume that uninstalling and reinstalling would have done the trick.
