### ISSUE TITLE
Discord Roll20

### ISSUE THREAD

**Issue by GracieFlow** [kakaroto/Beyond20#1157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Discord just recently connected with Roll20, but Beyond20 does not work within the Discord frame. Would love to see this happen if at all possible!

**Describe alternatives you've considered**

**Additional context**

**Comment by dmportella** [comment]
yeah i was thinking about it, its running in the electrum instance of discord, I will read up on the discord documentation but I dont think it will be easy to add a hook to it, unlikely that discord will allow that. 

May be Roll 20 Api 

/shrug

**Comment by kakaroto** [comment]
Roll20 sent a pull request to us to add support for the discord activity at the same time as they announced the feature, see : https://github.com/kakaroto/Beyond20/pull/1109
Unfortunately, there's an issue I've been unable (so far, mostly due to lack of time) to fix in order to merge the feature, but it should be available with an upcoming release.

**Comment by dmportella** [comment]
awesome, I did not know. I had a few people ask me recently if it was coming or if it was possible, I am glad roll20 devs and beyond20 are working together on this. <3
