### ISSUE TITLE
Quick (Dis)Advantage Persitent

### ISSUE THREAD

**Issue by mascent** [kakaroto/Beyond20#116]
When pressing (and subsequently releasing) the Ctrl/Shift button the addon does not always (or most of the time) recognize it. So we often roll with advantage or disadvantage without intending to.

Alt does reset.

I'm using Firefox v. 73.0.1

**Comment by kakaroto** [comment]
Hummm.. I had to try all sorts of things to reproduce the behavior. I can only get it to happen if I do for example Alt-tab or Ctrl-Tab or Ctrl-Shift-Tab to change windows or tabs. The problem is that the key press happens in the D&D Beyond tab, but the release happens in another window or tab, so it doesn't get registered.
I think the solution would be to reset all modifiers if the tab loses focus.
Thanks for the report! I hope this is the use case you're getting.
