### ISSUE TITLE
2024 Druid - Circle of the Sea - Emanate Wrath

### ISSUE THREAD

**Issue by Wazeau-deLierre** [kakaroto/Beyond20#1170]
**Describe the bug**
Level 4 druid, Circle of the Sea.   

**To Reproduce**
1. Go to Features and Traits / Class Features / Wrath of the Sea
2. Activate Wrath of the Sea via the Activate dropdown.
3. Go to Actions and scroll down to see Emanate Wrath
4. Note from the screenshot, there are 2 clickable icons, the first one rolls a d20 and adds 4, the second rolls one d6.  This is not correct.

**Expected behavior**
There should be 1 "B" to click and it should roll 4d6 (" To determine this damage, roll a number of d6s equal to your Wisdom modifier (minimum of one die)." - my character's wisdom mod is 4.

**Screenshots**
![Screenshot 2024-09-23 160206](https://github.com/user-attachments/assets/ee598ec1-0b15-44ab-8c59-63564640823e)

**Browser Info (please complete the following information):**
 - Chrome 
 - Version 129.0.6668.59 (Official Build) (64-bit)

**Additional context**
https://www.dndbeyond.com/characters/132508252

**Comment by dmportella** [comment]
Yep the HTML has two separate custom roll span tags hence it show wrong.

![image](https://github.com/user-attachments/assets/e59f23b6-ebbf-4b71-b826-cd766e59e88f)

**Comment by kakaroto** [comment]
> Yep the HTML has two separate custom roll span tags hence it show wrong.
> 
> Might not be easy to fix this. DnD beyond text on these actions/class features is annoying. :/

It's when they add a tooltip to say where that number comes from (the +4 in this case comes from the wisdom modifier, and you can see the tooltip will show `modifier:wis@min:1` ) and because of the separation of what is inside the tooltip and what is outside Beyond20 sees them as two separate things (as if they were separated with random text).
IIRC, the same thing happened with the fighter's second wind, and there's a fix for that. Hopefully the same fix can be applied here.

As you can see from the screenshot, only the `1d10` is captured, but rolling it does give the correct `1d10 + 15` formula.
![image](https://github.com/user-attachments/assets/6cb748ff-1559-4d6b-81ea-c91cc37d07bb)

**Comment by dmportella** [comment]
Makes sense.
