### ISSUE TITLE
D&D Beyond Encounters Combat Tracker Sync Issue

### ISSUE THREAD

**Issue by marshallvyper** [kakaroto/Beyond20#1172]
I'm not sure if this can even be fixed but I really enjoy using the D&D Beyond Encounters Combat Tracker and allowing my players to see the roll20 turn order so having them sync'd is awesome.  It works perfectly except when I have a dungeon with multiple encounters in it of the same monster (ie; goblin).  

If the player tokens are in room 1 with 2 goblins and I run the encounter, everything works however if the players go to room 2 first with different goblins, the sync puts the 2 goblins from room 1 in the turn order in roll20 instead of the two in room 2.  This becomes important when a player is moussing over the creatures in the roll20 turn order to highlight the token to know which is which.  I've tried selecting the goblins in room 2 first but it doesn't seem to help.  I've manually added the goblins from room 2 to the turn order, but the sync overrides them and switches back to room 1.

I roll initiative via the D&D Beyond system.  They get added fine, just the wrong tokens get added.

**Comment by kakaroto** [comment]
Hi,

Unfortunately, there's really no way of pinpointing which specific tokens in a map will match the enemies in an encounter other than through their names, and if you have the same type of monster in multiple areas of the same map, that can become a headache indeed.
I don't see how this could get fixed unfortunately, but the best solution I could suggest is for you to rename your goblins, since it all depends on the token names. So if after they're done with room 1, you rename the goblins in that room as "Goblin (ignore)" or "Goblin (room 1)" or "Goblin (dead)" or something like that.. then they won't match anymore and will be ignored by the sync of the combat tracker to encounter builder.
It's a bit annoying, especially if you have many of those, but I can't quite see another way of achieving that.
If you have ideas on how to do it, let me know and I'll reopen the issue if it's something doable.
Thanks.
