### ISSUE TITLE
[Website] Website Can't Connect Securely

### ISSUE THREAD

**Issue by ElvenChaos** [kakaroto/Beyond20#133]
The website [https://beyond20.here-for-more.info/](https://beyond20.here-for-more.info/) is broke.

I used both firefox and chrome and got errors regarding a secure connection.
Firefox gave the following error:

> Secure Connection Failed
>
>An error occurred during a connection to beyond20.here-for-more.info. SSL received a record that exceeded the maximum permissible length.
>
>Error code: SSL_ERROR_RX_RECORD_TOO_LONG
>
>    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>    Please contact the website owners to inform them of this problem.

**Comment by kakaroto** [comment]
Thanks for reporting it. I don't know why it's saying that. I don't actually manage the SSL certificate for that page. The website is automatically generated from the [docs](https://github.com/kakaroto/Beyond20/tree/master/docs) folder by Github itself using [Github pages](https://pages.github.com/)
I don't see any issues with it from my side with either FF or Chrome, is there a possibility that the problem is coming from your side? 
There's another person who contacted me in private to say that MalwareBytes is complaining about it. Do you have that installed by any chance and could it be blocking the site which is why chrome is showing that SSL error ?

**Comment by ElvenChaos** [comment]
I do, though I didn't realize Malware Bytes was blocking it. It seems to think there is a trojan for some reason.

**Comment by kakaroto** [comment]
Thanks for confirming. I don't know why Malware Bytes does this. Supposedly it's because the host itself (`here-for-more.info`) is considered unsafe but that'd be ridiculous since they'd be falsely triggering an alert on anyone using dyndns's services.
Not much I can do about it unfortunately. I hope it goes away on its own. :(

**Comment by kakaroto** [comment]
I've reported this to malware bytes over a week ago, I don't know if it made any difference but I haven't heard any new reports since.
https://forums.malwarebytes.com/topic/257976-beyond20-reported-as-false-positive/
Since there's not much more I can do. I'm closing this.
Thank you!
