### ISSUE TITLE
Discord: No option to input Secret Key?

### ISSUE THREAD

**Issue by RadicalRebop** [kakaroto/Beyond20#134]
> The Beyond 20 browser extension now needs to know where to send the rolls. Click the Beyond 20 options menu (the icon in the browser’s address bar), then More Options, then scroll down towards the end of the list of options for the Discord Secret Key field, just below the Discord logo and paste the key there.

I can not find the option. I scroll to the bottom and this is all Is see.
![unknown](https://user-images.githubusercontent.com/62270071/76817212-78b89a80-67bf-11ea-9b73-052aecede857.png)

**Comment by kakaroto** [comment]
That must be because you're still on the v0.9 version of Beyond20.
On the chrome store, I see it's still pending review, so I suggest you use Firefox for now to test it since v1.0 is already available on it.
![image](https://user-images.githubusercontent.com/27990/76817295-cf7e9e00-67d8-11ea-8df5-9084580b16b9.png)

**Comment by kakaroto** [comment]
Update: The release just hit the chrome store :)
