### ISSUE TITLE
UI: Error Box when no VTT Tab is open

### ISSUE THREAD

**Issue by jonberling** [kakaroto/Beyond20#148]
Currently, if you have no VTT Tab open and you open your character sheet on D&D Beyond you get a red error box letting you know Beyond20 could not find a VTT.

This UI is a bit annoying if you're like me where you visit your character on D&D Beyond quite a bit without playing on Roll20.

It would be nice if instead there was a more subtle UI element when Beyond20 couldn't find a VTT.

One suggestion would be to grey out Beyond20 button on your character sheet when Beyond20 can not find a VTT (the button that is between the character name and the share button). Then if the user clicks on the button display the error on the Beyond20 pop over.

That way I can continue to use D&D Beyond normally, especially since not all of my characters are used on Roll20.

**Comment by kakaroto** [comment]
Hi,
The warning used to be a dialog that you had to click 'ok' on.. having a small notification appear for 5 seconds when you open the page for the first time isn't a big deal in my opinion. It also serves as a reminder that there is no VTT, if the user wants to send their rolls to a VTT.

> This UI is a bit annoying if you're like me where you visit your character on D&D Beyond quite a bit without playing on Roll20.


I don't find the UI annoying personally, and I open DNB pages hundreds of times as I develop, without a VTT present. The first time you see it, you might find it weird, then you learn to ignore it, just like I'm sure you ignore the Beyond20 buttons that are there even if you're not using a specific sheet with roll20.
If you have ideas for how to make it more subtle, I'd be happy to oblige, but as it stands, I find this as minimally invasive (and still informative) as it can be. Do note that there is currently a bug #145 where it shows that warning even if you disable the hp syncing option since that warning actually comes from Beyond20 failing to update the character's HP with the VTT.
Also do note that if you set Beyond20 to send its rolls only to the integrated roller, then that warning won't appear (See Beyond20 options -> More options -> Select the VTT tab or game to send rolls to) 
![image](https://user-images.githubusercontent.com/27990/77534624-639ed400-6e6f-11ea-9859-ad661cf9729e.png)

> One suggestion would be to grey out Beyond20 button on your character sheet when Beyond20 can not find a VTT (the button that is between the character name and the share button). Then if the user clicks on the button display the error on the Beyond20 pop over.

I can't do that because I don't have a "live state" of every tab open in the browser. I can only know if a VTT is open or not after I try to send a roll (or the HP sync message) and it fails to find an open tab to receive the message. Using the integrated roller is also a valid use case, and greying out the buttons wouldn't be acceptable because the integrated roller is automatically used when you click the roll button and no VTT is found.

> That way I can continue to use D&D Beyond normally, especially since not all of my characters are used on Roll20.

Nothing prevents me from using D&D Beyond normally. That warning appears once when you update your HP, and disappears on its own after 5 seconds, it doesn't impede the use of the sheet in any way, and it's placed in an area where it wouldn't overlap the sheet itself, but even if it did, you can force dismiss it instantly by clicking on it.

With that being said, I'm closing this issue as wontfix, but feel free to comment further if you have additional suggestions.
Thanks!

**Comment by jonberling** [comment]
> Nothing prevents me from using D&D Beyond normally. 

Normal usage does not include regular error messages. All functionality may be there, but the _user experience_ has been significantly degraded. 

Assuming the error message was legitimate and the user had both a Roll20 tab and a D&D Beyond tab open it's not even clear what action the user could take. It is bad UX design to have such a low value warning displayed so prominently. 

Honestly, you'd be better off just changing the error message to a console log message.

If you want a UI element, hide it in the Beyond20 pop up.

If you want to keep it, then ask your users how they use it. If 99% of the item the answer is to ignore it that's a big hint that it should go. I am pretty sure that is going to be the answer, especially since you said this:

> The first time you see it, you might find it weird, then you learn to ignore it

Finally, do you accept pull requests? I looked at the in file dndbeyond.pyj. It seems to me adding an if check similar to this https://github.com/kakaroto/Beyond20/blob/master/src/dndbeyond.pyj#L292-L294 at line 280 would solve the bug you mentioned.

**Comment by kakaroto** [comment]
> Normal usage does not include regular error messages. All functionality may be there, but the user experience has been significantly degraded.
Normal usage does not include regular error messages. That's an error message related to there being an actual error. You use Beyond20 to sync D&D Beyond with a VTT, if no VTT is found, then it's an error. As for the UX being **significantly degraded**, I think that's a bit of a stretch to be honest. I'd like to think that the UX is significantly improved by the use of Beyond20.

>Assuming the error message was legitimate and the user had both a Roll20 tab and a D&D Beyond tab open it's not even clear what action the user could take. It is bad UX design to have such a low value warning displayed so prominently.
The error is legitimate, there wouldn't be an error if the user had both a R20 and DNDB tab open, and for a "no VTT found" error, the action the user should take is to open their VTT tab.

> Honestly, you'd be better off just changing the error message to a console log message.
Then I might as well remove it entirely. It's an error that happens, it should be visible to the user. If the user has to open their dev console to see the error to remind them that "oh, I forgot to open the VTT", then it defeats the purpose to telling them the VTT is closed.

> If you want a UI element, hide it in the Beyond20 pop up.
I don't understand this suggestion

> If you want to keep it, then ask your users how they use it. If 99% of the time the answer is to ignore it that is a big hint that it should go. I am pretty sure that is going to be the answer, especially since you said this:
> The first time you see it, you might find it weird, then you learn to ignore it

I've just asked my users on the Discord server. I would assume most people don't see that error, or they see it only if they open DNDB before Roll20/FVTT  and it serves its purpose of reminding them that they need to open the VTT window. I can guarantee that you '99% of the time' is not going to be the case. 
While you are right, that if "you learn to ignore it" is the default behavior, then it doesn't serve a purpose, but that only applies to people who would constantly open their sheets. I learned to ignore it because I open DNDB 1000 times a day during dev times, often without a VTT open as I test things. In your case, you also seem to be affected by it, because you use DNDB a lot without a VTT too.
I think the best solution here might be to have a character-specific option for where you want to send that specific character's rolls. That might actually be an interesting way of doing it as you could set a PC to always send to Campaign A and a different PC to always send to Campaign B, avoiding risk of mixing things up. In your case, your non-vtt characters could be set to only roll the integrated dice roller.

>Finally, do you accept pull requests? 
Yes, I definitely do and appreciate it whenever I get PRs, and that looks about right for the suggested fix.
I see you already sent a PR, so I'll go looking at that now.
Thanks! :)
