### ISSUE TITLE
Support Blood Hunter hemocraft die for Blood Curses

### ISSUE THREAD

**Issue by tdusnoki** [kakaroto/Beyond20#159]
If you click on a blood curse (only tried with "blood curse of the eyeless" you can roll on roll20 but it just rolls a d20 instead of a "hemocraft die" which changes after leveling up in Blood Hunter class. On level 1 it's only a d4.

**Comment by kakaroto** [comment]
That's a though one to handle. DNDB shows a `To Hit: -` which is why Beyond20 makes an attack since there's a to-hit property on the feature.
I also can't roll a hemocraft die for blood curses, like I do superiority die for fighter's maneuvers, since they don't all use a hemocraft die.. 
I'll have to read the class description carefully and see which features need to be handled specially.
Thanks for reporting it!
