### ISSUE TITLE
[Request] Roll initiative for multiple creatures at the same time

### ISSUE THREAD

**Issue by cgplayer2000** [kakaroto/Beyond20#181]
With the Group Initiative API script, you can select multiple creatures at the same time and individually roll initiative for them.  It'd be great to have that capability in Beyond20.

**Comment by kakaroto** [comment]
I assume this 'Group Initiative API' is a roll20 script thing?
I don't have a pro (or plus, whatever it's called) subscription to Roll20 so I don't have access to scripts. 
This is what Beyond20 uses for adding initiative : https://wiki.roll20.net/Dice_Reference#Roll_To_Initiative
I don't see anything about group initiative in there, and since I don't have a way of knowing if the user is a Pro/Plus subscriber I can't use scripts without it breaking for all those who don't have access to them.

**Comment by cgplayer2000** [comment]
Cool, thanks!

**Comment by SpectreWulf** [comment]
@cgplayer2000 You might try another excellent plugin called "VTT Enhancements Suit". It has lots of features that makes Roll20 a better experience IMO (even for Pro users). That includes rolling initiatives in a group and other QOL changes that once you use, you will never go back to vanilla Roll20.

**Comment by cgplayer2000** [comment]
Thanks for letting me know about VTT ES.  I'm set up on Chrome, and with it not reachable in the Chrome web store, I'm not going to be able to use it.  I'm happy with Beyond20 at the moment!  :-)
