### ISSUE TITLE
Support for Modifiers to Initiative

### ISSUE THREAD

**Issue by Jhazor** [kakaroto/Beyond20#188]
With the Wildemount books comes the Gift of Alacrity spell which allows you to add 1D8 to your initiative however currently theres no way to add any kind of modifier to initiative rolls beyond what is already calculated by dndbeyond

**Comment by RighteousPotato** [comment]
Surely that would be on DnDB to add? B20 just forwards the initiative they calculate.

**Comment by kakaroto** [comment]
Yeah, I'm unsure about this one too. I don't think it's D&D Beyond's or Beyond20's task of adding that actually. It's a spell, it has a duration, both DNDB and B20 have no way of knowing if you have cast that spell within the last 8 hours of in-world-clock in order to know if it should allow you to add the 1d8 or not.
Beyond20 is meant to help speed things up, it provides convenience, it doesn't do everything for you either. You, as a player, should know when you want to cast the spell and should know when to add its effects. Just like Beyond20 isn't going to track whether you are under the influence of Haste spell and automatically roll your attacks twice, it's not going to make assumptions on what spells you are under and automatically roll extra dice in specific situations.
If you have class features that affect initiative, like Dread Ambusher for example, you'll see that D&D Beyond calculates your initiative correctly, because those are fixed modifiers and not dependent on whether or not you are under the influence of a spell.
