### ISSUE TITLE
Discord: links to element website

### ISSUE THREAD

**Issue by frango9000** [kakaroto/Beyond20#189]
Hello, here is a suggestion for the discord bot.
On the embed messages:

-The character name links to character sheet
-The Weapon|Spell|etc name links to dnd beyond website for that element
-The footer links to beyond20 website  (https://beyond20.here-for-more.info/discord)

thx

**Comment by kakaroto** [comment]
Hi, thanks  for the suggestion!
- Linking to the character sheet was planned but not done due to lack of time (and seems I forgot that I still needed to do that because I hadn't written it down into an issue), 
- Linking to weapon/spell would be nice and was my original intent too, but I don't have any way of getting the link from the D&D Beyond sheet unfortunately
- Finally, I don't have control over making the footer a clickable link so I can't make link it to the website, though that was originally what I wanted as well.
