### ISSUE TITLE
Healing Word

### ISSUE THREAD

**Issue by Bizarbeltz** [kakaroto/Beyond20#19]
![image](https://user-images.githubusercontent.com/52081100/59937185-0f834100-9452-11e9-901e-35d79c0f2091.png)
I used Healing Word using the command "cast on Roll20" through the extension. Two dices were thrown and it took the highest (4) and then added the 3 to the final result (is the last 7 in the Roll20 chat). 
![image](https://user-images.githubusercontent.com/52081100/59937305-638e2580-9452-11e9-80eb-c8b63f4a5343.png)
And then I kept trying until in one of the throws it took the lower result (2) before adding +3.

The thing is that I don't get why it throws 2 dices if I have the auto advantage o disadvantage disabled. Sorry for being an inconvenience :(

**Comment by kakaroto** [comment]
Ah, thanks for the detailed report, and no, you're definitely not an inconvenience :)
I assume you're the one who reported the issue about Healing Word from the webstore, thanks for posting here!
So, I figured out the issue with Healing Word, it's basically the FAQ question answered [here](https://beyond20.here-for-more.info/faq#why-is-beyond20-rolling-too-many-damage-dice-on-roll20). In summary, the second dice rolled is the 'critical hit' dice. If you press the UP arrow in the text chat after sending healing word, you'll see what Beyond20 sent to the chat and you'll see a "Crit: [1d4]" which is why a second dice is sent. 
This is definitely a bug because there should never be any crit damage in this case since there is no 'To hit', so there is no possibility of critting.
Thanks for reporting, I'll fix it right away!
