### ISSUE TITLE
Roll20 shows popup asking for Initiative options

### ISSUE THREAD

**Issue by maxmiliano** [kakaroto/Beyond20#205]
When user clicks to roll Iniative from D&D Beyond, Roll20 tab shows a popup asking for Initiative options (type of advantage).

![Captura de Tela 2020-04-18 às 15 59 38](https://user-images.githubusercontent.com/997850/79668970-c3e31600-818e-11ea-9552-f32ed863a7d6.jpg)

**Comment by kakaroto** [comment]
This is not a bug, and I don't see a question.
You have it set to ask for advantage or to roll twice. Because it cannot roll for advantage twice since only one value can be added to the tracker, it asks you for it. I don't see a problem with this behavior.
If you have a more specific issue or question or suggestion, feel free to re-open this issue with more details.
Thanks

**Comment by maxmiliano** [comment]
Sorry to bother.

Indeed I have it set to "allways roll twice" (on Beyond20 settings).

![Captura de Tela 2020-04-18 às 17 37 22](https://user-images.githubusercontent.com/997850/79670731-86d15080-819b-11ea-8692-780000300746.jpg)

So if I don't want to select from the popup in Roll20 I would to have to change setting to "only roll once".
That's it?

**Comment by kakaroto** [comment]
yeah, if it's set to roll once, it won't ask.
