### ISSUE TITLE
Hi, I'm the Healing Word guy with new reports

### ISSUE THREAD

**Issue by Bizarbeltz** [kakaroto/Beyond20#21]
Sorry to bother, but I was checking with a friend and Cure Wounds and Moonbeam so far do the same stuff as Healing Word. It keeps rolling double dice because it recognizes the roll as Critical. Maybe all the healing spells are affected, and damage rolls from spells which require a Saving Throw from a target (Create Bonfire, Blight, Frostbite...) do the same thing.

It works fine with spells that require an attack roll first. The 1st level spells that have this condition can be thrown properly from the text since the dices are standard (besides healing spells). When it comes to higher level spells is when the thing gets messy.

Thanks for your hard work!

**Comment by kakaroto** [comment]
You're not bothering, thanks for the report! :)
I'm planning on releasing 0.4 today which has the fix I did for you 10 days ago. the fix is basically, if there is no 'to hit', then it won't roll crits, so Healing word, cure wounds, moonbeam would all be fixed by it. 
Let me know if you see anything else that's odd.
Thanks
