### ISSUE TITLE
hexblade's curse

### ISSUE THREAD

**Issue by nathanenns** [kakaroto/Beyond20#215]
Can there be an option for hexblade warlocks, to toggle the hexblade's curse to toggle the crit on 19/20 and adding proficiency bonus to damage rolls.

And on the subject of Warlocks, not sure if it would be easy or not, but is it possible to detect the invocations they have, and adjust damage rolls accordingly?  

IE: lifedrinker adding CHA damage to weapon rolls , I have already put in a request for dndbeyond to add the lifedrinker bonus to the weapon damage

**Comment by kakaroto** [comment]
1 - Hexblade's curse is already supported by Beyond20. See [FAQ](https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it)
2 - adding modifiers according to invocations/etc.. is up to D&D Beyond. Beyond20 only rolls what it tells it to, so that would be a no for the second question. The weapon should have "Pact Weapon" enabled on it, and D&D Beyond should automatically add the modifier in that case. If it doesn't, then it's a bug from their side.
