### ISSUE TITLE
Skill advantage granted by equipped item

### ISSUE THREAD

**Issue by Rarst** [kakaroto/Beyond20#229]
When equipped the boots of Elevnkind grant "You also have advantage on Dexterity (Stealth) checks that rely on moving silently."

It would be nice if this was added to Stealth rolls (probably in addition to regular roll, since it's only for sound),it's just the thing to keep forgetting to do. :)

Not sure if this is in scope / technically possible, searched through tracker, but didn't find anything related to such items. :)

**Comment by kakaroto** [comment]
This is more of a D&D Beyond thing **at this point** because Beyond20 doesn't have that kind of knowledge of which items you have equipped and what abilities they grant.
I know that they have the ability to add things like the advantage icon on initiative (which I use) or on saving throws (which I don't use yet), and I'm hoping they also do it for skill checks soon.
Once they do, I can use it to make that roll.
Same happened all the time with my players, wearing plate armor or chain mail and forgetting to roll stealths at disadvantage.

**Comment by Rarst** [comment]
FYI I just noticed that advantage marker now shows up on the Stealth skill in sheet, when Boots are worn (and clicking the skill even specifies that it's coming from the Boots and affects only sound).

I checked and equipping heavy armor adds disadvantage accordingly as well.

**Comment by kakaroto** [comment]
Yep! I knew it was coming, but didn't know when or if it was public knowledge, so didn't want to say anything. But that's what I've been waiting for in order to add support for it in Beyond20!
Moving the milestone to next release.
