### ISSUE TITLE
Staff of Thunder and Lightning attack

### ISSUE THREAD

**Issue by dalestringer3** [kakaroto/Beyond20#240]
You can roll for the attack just fine as if it is a quarterstaff but it doesn’t roll regular quarterstaff damage. When attacking with the Lightning, it also doesn’t roll the regular quarterstaff damage, just the lightning damage bonus.

**Comment by Aeristoka** [comment]
I believe this is because the Staff of Thunder and Lightning doesn't actually have an attack roll to be parsed:
![image](https://user-images.githubusercontent.com/7988297/81134493-29b2fa00-8f12-11ea-8275-910a13df2b99.png)

vs. a normal Quarterstaff
![image](https://user-images.githubusercontent.com/7988297/81134516-3df6f700-8f12-11ea-987b-191ea1a4ef59.png)

This is (if I recall correctly) something that DnDBeyond would need to change on the item itself.

**Comment by dalestringer3** [comment]
Well it says in the first paragraph that it attacks just as quarterstaff, which means damages too.

**Comment by kakaroto** [comment]
https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs
