### ISSUE TITLE
Sync AC with character sheet

### ISSUE THREAD

**Issue by figotech** [kakaroto/Beyond20#268]
Your extension has been such a life saver, I had to keep my roll20 charsheets updated all the time.

I pretty much use the green bar in tokens for HP (so nice how it syncs from DnDB to Roll20) and then I use the second sot to show AC (so that I can quickly check the token ac if they equip a shield or use magic armor etc....). could you make it so taht changes in AC in DnD Beyond also update the AC value in Roll20??

**Comment by kakaroto** [comment]
Thanks, but it goes closer to having the sheet synchronized than I'm comfortable with. AC should be generally pretty static, so you can change it yourself when needed.
I'm not going to implement character sheet import/migration/synchronization at the moment.

**Comment by figotech** [comment]
Well the reason I was suggesting it is because my players use inventory in DnD Beyond to equip/unequip shield (and they do this a lot in combat, they don't mind spending their actions). So this is a +/- 2 AC change.  I have my tokens set to show ac on bar2 so I can quickly check if a hit misses or does damage, so I end up having to ask them constantly and then update it.

Honestly with AC updating I would never have to bother again with the roll20 charsheet at all.

Anyway, thanks for such a great tool you have really done online gaming a breeze.

**Comment by Aeristoka** [comment]
> Well the reason I was suggesting it is because my players use inventory in DnD Beyond to equip/unequip shield (and they do this a lot in combat, they don't mind spending their actions). So this is a +/- 2 AC change. I have my tokens set to show ac on bar2 so I can quickly check if a hit misses or does damage, so I end up having to ask them constantly and then update it.
> 
> Honestly with AC updating I would never have to bother again with the roll20 charsheet at all.
> 
> Anyway, thanks for such a great tool you have really done online gaming a breeze.

Make the players report their current AC to you. Continue to not bother with the Roll20 character sheets, make them tell you their AC. If they misreport it low, that's on them.

**Comment by kakaroto** [comment]
I guess it's up to you on how you want to DM your own games.
What I did was that I would always tell my players "19 to hit, does it hit?" even if I knew what their AC was, as it gave them the opportunity to respond on every attack and made them more engaged in the combat. 
As for Beyond20 itself, it's meant to simplify rolling, but not automate everything, so I don't want to always make everything automated, otherwise we lose our jobs as DMs :p
I'll have to think about your use case, but at this time, I don't think I'd make that a priority even if I decided to go for it.
