### ISSUE TITLE
Initiative with Advantage - magic weapon

### ISSUE THREAD

**Issue by jrichview** [kakaroto/Beyond20#295]
I have a short sword of warning which grants advantage on Initiative when it's on your person. DNDBeyond displays the advantage icon. I have my settings set to "Ask every time" for advantage and it does not ask me when I roll Initiative. It just rolls without advantage.

Not a giant deal obviously because I can roll a 2nd time.

**Comment by kakaroto** [comment]
Hover your mouse on the roll, it will have been rolled with advantage. 
See my response in #275

**Comment by jrichview** [comment]
Well, no it rolled 2D20 and added my bonus. It should have rolled 1d20 + bonus 2 times.

**Comment by kakaroto** [comment]
that's not how advantage works. Read the PHB rules on how rolling with advantage works. You roll 2 d20s and take the higher value then add your bonus once.

**Comment by jrichview** [comment]
That's exactly my point. Beyond20 is rolling 2d20 + 4 and it should be rolling 1d20 + 4 twice

**Comment by jrichview** [comment]
Oh, I just read your other post. So this is not something roll20 allows unless I disable adding it to turn order.

**Comment by kakaroto** [comment]
ah, I misread, I thought you said "1d20 + twice my bonus" 
Yeah, having the rolls separate cannot work because it wouldn't know which of the two rolls to add to the tracker. It's essentially the exact same thing, you just don't see the breakdown of the two rolls.
The single roll that it rolls is correct, so not sure why you thought it was incorrect though.
