### ISSUE TITLE
Missing release process documentation?

### ISSUE THREAD

**Issue by moritonal** [kakaroto/Beyond20#297]
I'm looking to help out with this project, but I'm worried that any work introducing a better local development experience might have a knock-on effect on the release process.

I can't find any information about how the project is built and released and am assuming at the moment that it's a manual process by @kakaroto?

Would it be worth-while using something like Azure DevOps or GitHub actions to build and release major releases automatically to both Extension Stores?

**Comment by kakaroto** [comment]
Yep, it's a manual process. I just run `make build` which builds the extension zip using the webext program. It also used to compile all of the rapydscript files into javascript but that build process has changed recently, and I haven't gone through a release cycle since. (Looking at the makefile, I can see it wouldn't work actually, so I need to fix that anyway).
The process is manual but takes a few seconds, I manually delete the not needed files from the generated zip (docs file that are meant for the jekyll build, and I leave the md files) then copy the zip into a `-ff.zip` file in which I rename the `manifest_ff.json` into `manifest.json`. That's about it.
It then takes a couple of hours to write changelog, release notes, then uploading to chrome and mozilla store. I don't think there would be a way to automatically upload to the stores, as that would require my login credentials of course, I also wouldn't trust it to not mess things up (since one you upload to chrome store, it will lock it and you can't modify anything or cancel it, and it can take a week or more for chrome to review and approve the new version before it unlocks the interface).

So yeah, release process isn't complicated, if we don't care about the files that are not needed being in the resulting zip (just helps save a couple of KBs from the zip), then it's 'make build', copy zip, rename the firefox manifest file, then upload to each store. What's really complex is writing the changelog and release notes and there's no way to automate that.

**Comment by kakaroto** [comment]
Thanks for the package.json/gulpfile PR you sent in #300 which has made the release process much easier!
Here's the updated instructions : 
`npm run package`
I then have to add back the `manifest_ff.json` file into the firefox web ext artifact (so if that zip file is extracted and `npm run build` on it is run, it would not crash due to the missing file), I then have to copy the zip and remove the `src` directory from it (because Firefox does js validation on all included js files of a package when I upload it, and it was failing verification because of the `sandbox-header.js` and `sandbox-footer.js` files which had invalid syntax.
I'll need to update the gulp scripts so it does this automatically for me next time. 
As for your suggestion of having github actions pushing to the stores, that's probably going to be no, because it would require me to put in my credentials into some file, which I wouldn't trust, and I'd prefer to do it manually anyway (it's really not complicated once I have the zip files generated) as it also involves (for the Firefox part) posting the release notes and possibly some instructions for the reviewers.
Is there anything missing from the README with regards to build/release process (or anywhere you think would be a good spot to put down this documentation) or do you consider this issue to be fixed ?

**Comment by kakaroto** [comment]
Closing this as I believe there's nothing further to do.
