### ISSUE TITLE
Casting Magic Missile is inconsistant

### ISSUE THREAD

**Issue by Ryex** [kakaroto/Beyond20#303]
Hi, I have s Sorc getting very frustrated with casting Magic Misle via Beyond 20 in Roll20.

The main issue is the output is inconsistent.

Clicking the "Cast" button in the spell list will roll always ONE dart. not the 3 for a first level, not the additional darts of uplevel casts.

uplevel casts will display "Higher Level Cast" in their description

![image](https://user-images.githubusercontent.com/508861/83096311-92e5e300-a062-11ea-9515-3a8c914e6144.png)

Opening the spell in the sidebar and Clicking "Cast in VTT"

Will sometimes roll the 3 dice for a level one cast.
Will Sometimes only roll the 1 or 2+ additional dice for the uplevel cast.
Will Sometimes roll all dice both the 3 initial and the additional.

![image](https://user-images.githubusercontent.com/508861/83096467-f7a13d80-a062-11ea-9733-0243657d2bcd.png)

Clicking the "Spell Slot" button next to "Cast:"  and slot level selection in the side bar will behave as the "Cast in VTT" button but on occasion can cast anywhere from 1 bolt to 7 bolts even when 1st level is select if you've been playing around with the spell level selection. appearing to cast the current spell level and the previous spell level simultaneously but mark all rolls as the current level.

I realize that Magic Missile is actually one of the most complex behaviors so I'm not suprised that this is a bug, If there is any help I can provide in debugging this behavior I'm happy to help.

![image](https://user-images.githubusercontent.com/508861/83096992-397eb380-a064-11ea-8446-cd85ebcbe1ae.png)

**Comment by Ryex** [comment]
perhaps the listing of (3 darts) could be rolled
and then the listing of "Aditional darts: #" could be rolled?

**Comment by Aeristoka** [comment]
This is not a bug, this is an issue with Roll20 lagging, and receiving the messages multiple times.

**Comment by kakaroto** [comment]
> This is not a bug, this is an issue with Roll20 lagging, and receiving the messages multiple times.

@Aeristoka I don't think that's the case here, they're asking about the damage rolls themselves if I understand it right.

> perhaps the listing of (3 darts) could be rolled
and then the listing of "Aditional darts: #" could be rolled?

@Ryex Beyond20 will always roll the same thing : The damage that D&D Beyond tells it to, which is 1d4 + 1
It will never roll more than one missile at a time. Your player would need to click the "Cast on VTT" button 3 times to get 3 rolls. I just had a discussion yesterday about this on my discord, here's the log : 

> KaKaRoTo Yesterday at 4:52 PM
it's being sent once only on purpose, because you can split to separate targets, but also because D&D Beyond gives me the damage for only one missile. If you cast it at a higher level, it will be more than 3 missiles as well. There's another similar spell, scorching ray where you send multiple rays for the attack
Having to click 3 times makes perfect sense to me, you are launching 3 missiles, so you click 3 times to launch each one.
Also, I don't want people being stuck having it roll 3 missiles if there are circumstances where they only want a single missile (example: you say "I roll at 2nd level" but then you click on 1st level, so now you're missing 1 missile, and you have no way to roll a single one independently)

> Oshy Yesterday at 4:58 PM
It subtracts from the spell slots when you click it 3 times from your spells list so you just need to know how that behaves

> KaKaRoTo Yesterday at 4:59 PM
nope, Beyond20 doesn't touch the spell slots at all
If you use D&D Beyond's own "Cast" button, it will substract, but if you use Beyond20's button, it won't

Note that technically, the RAW is that you roll 1d4+1 once and them apply that same damage for each missile, though I know most people don't use the rule as written (I didn't in my game either).

I realize now that *maybe* Aeristoka got it right and your issue is that it rolls more than once on a single click ? In which case, see #154 which is the issue where Roll20 rolls more than once. Also make sure your player doesn't have multiple Roll20 tabs open, which would make it send it to each tab separately and duplicate all rolls.

**Comment by Ryex** [comment]
um... Note to be rude by saying that your wrong, but Magic Missile is the ONLY roll that has EVER had this problem, both I and my player can only duplicate the multiple rolls for ONLY this roll.
No extra clicks, only one roll20 tab open.

This seems inconsistent with the explanation that roll 20 is lagging.

**Comment by kakaroto** [comment]
Yeah, it wouldn't make sense as there is no special handling of Magic Missile, and it gets rolled just like any other spell (which is why you have to click it more than once. It sees D&D Beyond's damage of "1d4 + 1" and that's what it rolls).
With that in mind, give it another try and see if you can replicate any of the behavior you said you saw. And if you see multiple rolls, make sure there are no other tabs open to Roll20 and try other attacks to see if it happens there too.
I hope that helps.

**Comment by Jhazor** [comment]
strictly by the book wording you roll 1d4+1 and that applies to all the darts

https://twitter.com/JeremyECrawford/status/774030989894955008

**Comment by Aeristoka** [comment]
> strictly by the book wording you roll 1d4+1 and that applies to all the darts
> 
> https://twitter.com/JeremyECrawford/status/774030989894955008

Super Duper more fun to watch my wizard roll all 1s for the damage die though
