### ISSUE TITLE
Roll max

### ISSUE THREAD

**Issue by icemann19468** [kakaroto/Beyond20#31]
first off not a programmer.  But i have found that in firefox when it says a d4 on spells and you click on it to roll the d4 in roll20 its always the number after the "d" looks like its missing the "1" in 1d4 in most of the spells like bless or bane hope this helps.

**Comment by kakaroto** [comment]
Hi @icemann19468 and thanks for the report.
I'm unable to reproduce the bug here. I've tried in both Chrome and Firefox, and it rolls a d4 every time. With 3D dice enabled, I can see a d4 dice being rolled as well. 
I've tried the Bless and the Bane spells as you suggested. I've also tried clicking on the 'd4' from withing D&D Beyond as well as from the spell description in Roll20 and in Foundry VTT from when we display the spell. It works in all cases.

![image](https://user-images.githubusercontent.com/27990/63654839-b08dc100-c74d-11e9-9ac6-8ccdb4dce438.png)

I assume you have the latest version of Beyond20 but make sure you do just in case (version 0.5 is the latest), and if using Roll20, can you press the up arrow in the chat to see the latest message that Beyond20 sent, and paste it here so I can see if it's wrong somehow ?

Thanks.

**Comment by icemann19468** [comment]
i see what you mean, it seems it works i just rolled like 5 maxs  sorry

**Comment by kakaroto** [comment]
Ha, well then that's good to know! You're lucky and there's no bug for me to fix :)
Make good use of your luck, and enjoy the game.
