### ISSUE TITLE
Silver Tongue: Bard College of Eloquence

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#327]
From the new Mythic Odysseys of Theros
https://www.dndbeyond.com/classes/bard#CollegeofEloquence

Silver Tongue
3rd-level College of Eloquence feature

You are a master at saying the right thing at the right time. When you make a Charisma (Persuasion) or Charisma (Deception) check, you can treat a d20 roll of 9 or lower as a 10.

Similar to Rogue Reliable Talent, but specific to ONLY two Skills

**Comment by kakaroto** [comment]
that sounds fun... 
Note: If you're sending a PR for something, you don't need to open an issue about it first. Issues are (for me) a way to not forget about something that needs fixing and to document what the problem is. If there's a PR for it, then it's already documented and isn't likely to be forgotten. Creating an issue is just doubling the maintenance work for you and for me.
