### ISSUE TITLE
Chaos bolt

### ISSUE THREAD

**Issue by Jhazor** [kakaroto/Beyond20#344]
chaos bolt has a box asking for a damage type before the roll My assumption is it's picking up the same thing chromatic Orb does but that conflicts with the special case stuff you've had to do for Chaos bolt in the past because the drop down is empty

![image](https://user-images.githubusercontent.com/59282727/83615139-0cf3fb80-a57e-11ea-87c8-4bd722222799.png)

**Comment by Aeristoka** [comment]
With or without Digital Dice turned on?

Do you have a character sheet link I can test with?

**Comment by Jhazor** [comment]
both with and without digital dice 

ddb.ac/characters/10518046/K16CoR

**Comment by Aeristoka** [comment]
> both with and without digital dice
> 
> ddb.ac/characters/10518046/K16CoR
> 
> Just in case - the dialog box is unneeded, the damage type is determined afterwards by the diceroll (and i assume that would be a far too complex thing to code in)

This bug was caused by the new resolveRolls call that @kakaroto implemented to handle rolling with Digital Dice (it's used for ALL rolls now, but allows using Digital Dice).

The crux of the issue was, with the new paradigm, Chaos Bolt was now looking at empty results, as no roll had happened yet. My fix simply moves the Chaos Bolt processing after the resolveRolls call to let the Chaos Bolt processing have results to work with.

**Comment by Aeristoka** [comment]
> chaos bolt has a box asking for a damage type before the roll My assumption is it's picking up the same thing chromatic Orb does but that conflicts with the special case stuff you've had to do for Chaos bolt in the past because the drop down is empty
> 
> ![image](https://user-images.githubusercontent.com/59282727/83615139-0cf3fb80-a57e-11ea-87c8-4bd722222799.png)

I actually went and looked at Chaos Orb to compare, this is actually some interesting coding.

The primary difference is:
Chaos Orb, you choose up front
Chaos Bolt, the dice Results give you your choices
   There is a LOT of special coding around this, as the 2 D8s give you the two different choices for damage. OR if they are equal, the damage is fixed to that one type, AND you get to do a new attack as it leaps. Neat little chunk of code (that just needed to be moved due to the new resolveRolls)
