### ISSUE TITLE
Make rolls trigger pressing the dice icon with Quick Roll areas

### ISSUE THREAD

**Issue by Urkaz** [kakaroto/Beyond20#353]
I've been testing the new changes introduced in 2.0, and I liked the Quick Roll areas, but it was a bit confusing for me as each time the dice pop-up icon appeared, I tried to press it instead of the number.

I suggest moving the "click" area to trigger the roll to the dice pop-up that appears when hovering a number, this way, you can click on the number to open the description (for example, the Initiative is harder to open with this setting enabled) and then click on the dice pop-up to make the roll.

Also, related to the Quick Roll areas, using Shift to make them with Advantage roll, makes my browser (Chrome) highlight random fragments of text. Clicking on the dice pop-up is not highlighting anything.

Finally, you can apply to the css "cursor: pointer;" property to the dice pop-up so it appears clickable when the mouse is over it.

I tried to explain in this gif the problem with the highlight with Shift, and the suggestion of pressing the dice pop-up with the "cursor: pointer;" applied:
![beyond20](https://user-images.githubusercontent.com/521864/83667241-6126cc00-a5ce-11ea-9b16-99d6950aff25.gif)

**Comment by Aeristoka** [comment]
This was considered and tested, but was discarded. The Quick Rolls have ALWAYS been clicking on the actual thing you're asking to roll.

**Comment by kakaroto** [comment]
A couple of things. At first, I didn't want to interfere with the digital dice of DNDB, which is why I made the quick roll area remain visible if you move your mouse over it and give 1000ms as you exit the previous area before it disappears (to give you time to click on it). The icon with the arrow was also there specifically to tell people "click here".. and it was great.
Then I was told by someone that this doesn't work for people using mobile/touch devices because they can't hover+click. So I had to change it and revert back to the previous behavior of clicking on the area itself, but I left the behavior of the tooltip and icons (decreased the timeout from 1000ms to 100ms which is still actually good enough for moving the mouse to it).
I actually think having the quick roll tooltip clickable makes a lot of sense, and so I think I need to implement this.
Thanks for the CSS idea, will definitely use it, as I think it makes it nicer!
