### ISSUE TITLE
Dragon's Breath Doesn't Ask for Damage Type

### ISSUE THREAD

**Issue by Haravikk** [kakaroto/Beyond20#356]
I've only just started checking out Beyond20 so apologies if I've managed to miss a report about this. Also I wanted to say a huge thank you for working on this, and I'm impressed at the speed with which integration with D&D Beyond's dice roller has been added!

The issue I'd like to report is with the spell Dragon's Breath from Xanathar's Guide to Everything; this basically gives a character a Dragonborn breath weapon attack, with a choice of five damage types (acid, cold, fire, lightning or poison).

When casting this with Beyond20 though no choice is given, it instead rolls a very generous 15d6; thankfully it recognises the different damage types and breaks them down in its results on Roll20, so we can still get the correct value. My understanding is that similar spells (such as Chromatic Orb) ask for the correct damage type before rolling, so if it's possible to do the same that would be ideal I think?

Thanks again!

Edit: This also seems to be affecting Hunter's Mark (rolls damage for bludgeoning, piercing and slashing all at once).

**Comment by kakaroto** [comment]
Answering here with regards to Hunter's Mark.
That one is specific to the weapon damage as @Aeristoka said, and there are plenty of spells that do that (see magic Weapon or whatever). I don't want to start handling every case. In those situations, you roll and take the damage appropriate for your weapon OR always take the first damage and ignore the rest (needs to be pre-determined with your DM and consistent throughout your games).
There are too many special situations like these and I don't want to start adding logic specifically for them because Beyond20 is meant to make things easier to roll, and I think it does that already, having it also work around potential display inconsistencies in D&D Beyond, that's a plus. I did it for chromatic Orb only because the number of different results was so high that it made it nearly impossible to read the damage because there were like 8 or 10 different values, which was ridiculous. Dragon's breath is at the limit (in my opinion) of that as well. If it's just bludgeoning/piercing/slashing, I think players can ignore a couple of values on their own.
Hope that helps clarifies it and how I want this to work moving forward.

**Comment by Aeristoka** [comment]
I concur with @kakaroto completely on this.
