### ISSUE TITLE
Brutal Critical doesn't work with Perfect Rolls Crit option

### ISSUE THREAD

**Issue by Flinx-7** [kakaroto/Beyond20#357]
I was playing around with a level 20 Barbarian character, and I noticed that when I rolled a critical hit, it did not roll any extra damage for my Brutal Critical class feature.  I double checked to see if the "Brutal Crit/Savage Attacker" feature was toggled on, and it was, so I went to discord to check for help, and while I was waiting for a reply, I played around with a few other settings, and noticed that if I turned Critical Hit rule to "Standard PHB Rule" it suddenly started working correctly (I had "Homebrew: Perfect Rolls" turned on before that because that is what rule our gaming group uses.)

Here is a screen shot of what showed up when it didn't work:

https://i.imgur.com/AlfAvOt.png?1 (Yes, I rolled 2 20s on that roll :D )

**Comment by Aeristoka** [comment]
@Flinx-7 Submitted my Pull Request with a fix for this:
![image](https://user-images.githubusercontent.com/7988297/83697182-97a71b80-a5bb-11ea-8566-0cc2bd7f4884.png)

**Comment by clownphish** [comment]
There's still something wrong with how this is calculated under certain conditions. The one I've found is when calculating the brutal critical using a weapon that has 2dx magical bonus damage (like a Flame Tongue Greatsword, for example). Instead of maxing two of the damage dice, it maxes more (e.g. 4d6). It does work correctly for regular weapons without the magic bonus damage and weapons with 1dx of magic damage (e.g. Flame Tongue Greatsword is a problem; Frost Brand Greatsword is not)

The Beyond20 Roll Renderer shows the calculation reasonably clearly. Here's two examples (my explanations in brackets):

**Barbarian with incorrect calculation (Flame Tongue Greatsword)**
Flame Tongue Greatsword    {14} (to hit)
Slashing Damage    15 (2d6+4)
Fire(While Flaming) Damage    10 (2d6)
Rage Damage    3
Slashing Critical Damage    12 (2d6 maxed)
Fire(While Flaming) Critical Damage    12 (2d6 maxed)
Brutal Critical Damage    24 <<< I think this should be 12, or 2d6 maximized
Totals
Total Damage    28
Total Critical Damage    48

**Barbarian with correct calculation (Frost Brand Greatsword)**
Frost Brand Greatsword    {28} (to hit)
Slashing Damage    11  (2d6+4)
Cold Damage    5 (1d6)
Rage Damage    3
Slashing Critical Damage    12 (2d6 maximized)
Cold Critical Damage    6 (1d6 maxed)
Brutal Critical Damage    12 (2d6 maxed) << I think this is correct
Totals
Total Damage    19
Total Critical Damage    30

**Comment by kakaroto** [comment]
Do you have a sheet we can test this with ? 
Reopening the ticket until we investigate it

**Comment by Aeristoka** [comment]
> Do you have a sheet we can test this with ?
> Reopening the ticket until we investigate it

I think I kinda see the issue here... I think it wasn't noticed because of the Homebrew option not being very widely used vs. Rules As Written.

**Comment by clownphish** [comment]
Sure! https://www.dndbeyond.com/characters/28892195 has both the Flame Tongue Greatsword and the Frost Brand Greatsword you can replicate the above with. Let me know if this wasn't what you meant :)

I did go on to the Discord channel to repot this too and was told that this issue was being investigated under ticket https://github.com/kakaroto/Beyond20/issues/305  (apologies, I should have posted this link back here I think). I can't tell if that logic/fix will apply here too though. Thanks!
