### ISSUE TITLE
FVTT: Using the "Apply Damage" dropdown on Beyond20 damage seems to remove "attributes.hp" from the token's bar 1 options

### ISSUE THREAD

**Issue by smffraser** [kakaroto/Beyond20#36]
As title says. Tested on both damage roll from Foundry vs damage roll from Beyond20. Looks like when using the "Apply Damage" drop down for the Beyond20 damage roll, the "attributes.hp" options get deleted from the token's bar drop down. My screen recording is too big to attach so will send via discord.

**Comment by kakaroto** [comment]
Looks to me like a bug in FVTT. the "apply damages" appears if the content has an element with a `dice-roll` class, but then it checks for `dice-total` to apply, but since it doesn't find it, it will set the hp to `null` (which is in itself a bug). I also can't change the span element to use a different class, because the CSS for the tooltip (which is generated by the core FVTT template) only applies to descendents of a `dice-roll` class. So... potential fixes in FVTT  : 
- FVTT checks for existence of `dice-total` instead of `dice-roll` before deciding to show the 'apply damage' context menu
- FVTT CSS for the roll tooltip should be using the selector `.dice-tooltip` and `.dice-formula` instead of  `.dice-roll .dice-tooltip` and `.dice-roll .dice-formula`
- If more than 1 dice-total is found, the `Actor5e.ApplyDamages` should pop a notification asking the user which damage to use instead of concatenating their values
- If resulting HP that gets calculated is not a valid number, it should not update the actor HP
- If a Bar attribute's value is non-valid (`null` in this case), the Token config sheet should not display that the selected attribute is `None` because it can confuse the user in thinking the bar setting changed when it's just its value that is not valid.

And for the actual fixes I'll want to do in Beyond20, it would be to add the `dice-total` on the "Total Damage" line so it can be picked up and not have it set in attack/skills rolls for example
