### ISSUE TITLE
Condition synchronization is incompatible with Obsidian module in FVTT

### ISSUE THREAD

**Issue by TheGalidor** [kakaroto/Beyond20#372]
When using the Obsidian Module in FoundryVTT condition updates will not be synchronized. The syncing seems to fail in either direction: updating a token will not update the DnDBeyond sheet, and toggling a condition on DnDBeyond will not update the token.

I already did a little bit of debugging myself and can confirm that the problem is probably just a compatibility issue due to how Obsidian handles conditions. Following the update message will lead to [this function](https://bitbucket.org/Fyorl/obsidian/src/f765d096dafd3f3d923e9c45b0c1937947697c29/js/rules/conditions.js#lines-33) which causes the correctly applied updates to be overwritten by the Obsidian module.

**Comment by kakaroto** [comment]
There is no syncing from a VTT into D&D Beyond. Beyond20 is a passive reader of D&D Beyond only.
As for conditions on the token in Foundry, the sheet should be irrelevant. You need to have the Beyond20 companion module installed for the conditions to be set.
That link to obsidian however seems to indicate that Obsidian ignores all effects and just draws its own conditions, which means there is no way of making it work with obsidian. I think Obsidian here is wrong and really shouldn't be completely overriding status effects. It should add its own conditions to the list, not override it, and so this is a bug in Obsidian, so not sure why the issue was created here.
I'm closing this, feel free to re-open it if you think that Beyond20 itself has a bug.
