### ISSUE TITLE
Damage output bug for custom weapons

### ISSUE THREAD

**Issue by joshbell56** [kakaroto/Beyond20#4]
![2019-05-09 (2)_LI](https://user-images.githubusercontent.com/50472024/57498679-72ee5080-72a2-11e9-84fa-cf6b6970ea95.jpg)

As you can see in the first image where the arrow is pointing, there is a modifier added that gives +1 piercing damage to the weapon.

![2019-05-09 (4)_LI](https://user-images.githubusercontent.com/50472024/57498705-9c0ee100-72a2-11e9-8956-8758531eab64.jpg)

In the second image you can see that it's putting that +1 with the +7 and creating a +71 when it should be +8 total.

**Comment by kakaroto** [comment]
Thanks for the report. Yes that's not right, and I finally found how you can create a custom item, the homebrew part in dndbeyond is pretty cool! :)
I'll try to have that fixed soon!

**Comment by joshbell56** [comment]
> Thanks for the report. Yes that's not right, and I finally found how you can create a custom item, the homebrew part in dndbeyond is pretty cool! :)
> I'll try to have that fixed soon!

Like I said, there is a workaround, so it's not a huge deal. But, again, I thank you for all of your hard work!

**Comment by kakaroto** [comment]
I had the same issue 2 days ago in a game using "Flame tongue shortsword" because it has additional damage "while flaming" the "while flaming" was also being added to the damage which prevented the dice formula from being recognized. 
I create a custom weapon with all sorts of weird damage, and it works properly now. Thanks for reporting the bug!

![image](https://user-images.githubusercontent.com/27990/57816543-ac630800-7749-11e9-93b6-f569e85a1041.png)
