### ISSUE TITLE
Biased die rolls

### ISSUE THREAD

**Issue by taekahn** [kakaroto/Beyond20#406]
The way the rolls are calculated is biased and will not produce equally likely results across the entire range.    
Suggestion:
Replace 
```
let die = Math.floor(Math.random() * this.faces) + 1
```
With 
```
let Random = require("random-js");
let random_engine = Random.engines.mt19937().autoSeed();
...
let inclusive_range = Random.integer(1, this.faces);
let die = inclusive_range(random_engine);
```
To make the rolls fair.

**Comment by kakaroto** [comment]
Hi,
This was explored already and you are wrong.
First, this is using pure JS, I won't be using any sort of `require` statement and switching to browserify or whatever is needed to generate the files. There are also much simpler and self container Mersenne Twister implementation, like the one included in Foundry VTT's code.

Second, this may have been true over 5 years ago, but it's not true anymore.

Here's part of the discussion that happened about this a few months ago on Discord : 
> Mersenne Twister is worse than almost any random generator made after 2015. Math.Random doesn't actually generator numbers, it tells the browser to, and most modern browsers use Xorshift128+ which is on the very high end of Pseudo Random Number Generators.
Point being, if you're using a browser made in 2016 or earlier, you're probably fine.
Unless some hipster made their browser use some really silly code,  Mersenne Twister is actually worse than the core

You can read about the algorithm used by v8 (Chrome and all Chromium based browsers) since 2015 which is xorshift128+ : https://v8.dev/blog/math-random
And you can see that Mozilla also switched to it 5 years ago : https://bugzilla.mozilla.org/show_bug.cgi?id=322529
If someone is using a browser from 2014 and hasn't updated it since, then the fact that the dice rolls may be biased will be the least of their problem.

**Comment by taekahn** [comment]
Mersene twister was just an example. I was not raising it up as an ultimate random number generator.  
The fact that that is what you're pointing to is betraying your ignorance.  
It has nothing to do with the method with which a random number is generated and everything to do with how it is selected.  

**The fact is** using multiplication for fitting a randomly generated number to a range introduces bias. It is unequivocally an incorrect way to select a random number within a range.  
You can find out plenty about it by googling, but here is a site that explains it.  
https://pthree.org/2018/06/13/why-the-multiply-and-floor-rng-method-is-biased/  
This will be true forever.  

Your rolls _are_ biased. If you're ok with that, then you're ok with that.

**Comment by kakaroto** [comment]
You suggested changing the code from `Math.random` to using the `random-js` module using MT (which is the only algorithm it adds from native browser random). You didn't say that the issue was the floor/multiply method. 
That fact betrays your ignorance in knowing how to create actionable issues. And your last comment betrays your inability to speak properly without attitude and insulting people.
Even if I was going to fix this, you've pissed me off enough right now by your shitty attitude that I don't even want to read more of your hollier-than-though preaching.

I guess I am ok with Beyond20 being biased.

**Comment by taekahn** [comment]
I'm sorry, i _i don't do js_. I don't know the ins and the outs of how the projects are put together and what people do and don't prefer to use.  
It was an example.  Nothing more. Or else, as previously stated i would have done it as a PR.

>  I actually care about Beyond20 not being biased, but now thanks to you, I don't.

If you actually cared, you personal feelings for me wouldn't stop you.

**Comment by shadow7412** [comment]
Personal feeling aren't hte problem here - it's your misunderstanding that @kakaroto is donating their time to make this plugin for all of us - and you need to respect that.

A phrase like "betraying your ignorance about what is wrong with your code" is completely inappropriate in any situation, but especially toward a volunteer. To follow that up with "I don't do js" completely invalidates your opinion as it proves that you're parroting a (probably more than 5 year old) article rather than actually knowing what you're talking about.

If you're so worried about it, then I suggest learning a bit of JS and raising your own PR. Until then, I suggest learning how to talk to people.

**Comment by taekahn** [comment]
>  "I don't do js" completely invalidates your opinion as it proves that you're parroting a (probably more than 5 year old) article rather than actually knowing what you're talking about.

No. Sorry, but you're wrong.  
Incorrect math is incorrect math. The language is irrelevant.

**Comment by shadow7412** [comment]
You've missed the point - your attitude is a much more critical bug than the math.

**Comment by taekahn** [comment]
No, i read that part, but my attitude isn't part of the program. So i ignored it.  It seems you want to talk about this, posting this. I was going to let it drop after that last post.  
You want to discuss my attitude we can discuss my attitude.  

> A phrase like "betraying your ignorance about what is wrong with your code" is completely inappropriate in any situation, but especially toward a volunteer. 

It is a factual statement. If it hurts someone's feefees, i'm sorry.  That's how i talk.
Everything is offensive to someone.
Trying to figure out if some random stranger on the internet is going to be offended by what you are going to say is an exercise in futility.
