### ISSUE TITLE
Ability Checks add +1 and the modifier

### ISSUE THREAD

**Issue by zchjhnsn** [kakaroto/Beyond20#424]
All skill checks, saving throws, attacks, and spells work but when I try to do one of the six ability checks it rolls " 1d20 + the modifier + 1" on Roll20. 
![image](https://user-images.githubusercontent.com/67570104/85969702-0b0b3580-b98e-11ea-9fe3-86376b437fb5.png)

**Comment by kakaroto** [comment]
Check your character specific settings in Beyond20 (the Beyond20 button next to the name) for any custom modifier you may have added.

**Comment by zchjhnsn** [comment]
Just checked and there are no additional modifiers added in the Beyond20 settings.

**Comment by zchjhnsn** [comment]
I just removed the extension and reinstalled it and set it to the settings I liked. No more +1 to my ability checks. Strange...

**Comment by zchjhnsn** [comment]
This issue returned again. 
![image](https://user-images.githubusercontent.com/67570104/86498905-aebd6280-bd4d-11ea-828a-762af6b74a87.png)

**Comment by zchjhnsn** [comment]
This issue returned again. 
![image](https://user-images.githubusercontent.com/67570104/86498920-bed54200-bd4d-11ea-94fe-beffbb03a5ea.png)

**Comment by kakaroto** [comment]
Can you screenshot the character's custom settings please ?

**Comment by zchjhnsn** [comment]
![image](https://user-images.githubusercontent.com/67570104/87091539-76130280-c1ff-11ea-8c8e-b16dc1891ed2.png)

**Comment by kakaroto** [comment]
Ah, thanks for the screenshot, that's helpful!
The +1 is your half proficiency from jack of all trades since D&D Beyond doesn't add them to the raw ability checks (only to the skill checks).
I hadn't even thought of it until I saw the screenshot, and hadn't noticed your complaint was specific to raw ability checks.

When you uninstalled/reinstalled the extension, it deleted your settings and didn't know you had Jack of All Trades until you clicked on the features tab (See [FAQ](https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it) for explanation)
The mystery is solved! :)
