### ISSUE TITLE
When using Digital Dice and Custom Roll Formula, Roll20 still bases Crit Fail or Crit Success on bonus die

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#452]
This may be tied to the fact that Digital Dice isn't querying for a custom roll formula.

Here are two examples... When rolling an attack roll, Digital Dice is auto-adding my bless formula. The two images show a roll of 1 and 4 being added, despite not querying for it. They then take the total (with that 1d4 roll) and add a 0. So it appears as though, by ignoring the query it's actually adding both the "Yes" 1d4 and the "No" 0.

![image](https://user-images.githubusercontent.com/19612384/87227702-d7a3b000-c36a-11ea-8b02-3fa0ba21381b.png)
![image](https://user-images.githubusercontent.com/19612384/87227699-d4102900-c36a-11ea-9b99-0312ef672064.png)

**Comment by kakaroto** [comment]
Yeah, Digital Dice won't query a custom roll formula since that query format is specific Roll20 format and only works when the roll is executed on Roll20. It's not adding both results but rather parsing the formula as "1d4|No,0" was the dice formula, which ends up being executed as "1d4" as it doesn't understand what comes after it (i.e: it's not a valid modifier like "kh1" for example).

But this is a valid bug where custom dice modifiers shouldn't affect the crit/fail status of the result.
Thanks!
