### ISSUE TITLE
Request: Magical Modifier on raw ability checks

### ISSUE THREAD

**Issue by pandanielxd** [kakaroto/Beyond20#478]
Hey! This might be a little bit too specific, but I thought it would be worth mentioning anyway.

The magic item **Stone of Good Luck (Luckstone)** does the following on attunement:
_While this polished agate is on your person, you gain a +1 bonus to ability checks and saving throws._

DNDBeyond automatically applies this to all skill checks and saving throws (well every one of them except for Death saves, but I saw that that is already being worked on), but it does _not_ work with the raw ability checks like Strength, Dex, etc. even though they are also ability checks.

An example: 
![image](https://user-images.githubusercontent.com/65407753/88793823-bd0c6c00-d19d-11ea-96f9-3a02e73236de.png)
![image](https://user-images.githubusercontent.com/65407753/88793832-c0075c80-d19d-11ea-8854-23f998e6928d.png)

This works the same with Jack of All Trades from Bards, but there Beyond20 actually does add the bonus score with an option:
![image](https://user-images.githubusercontent.com/65407753/88793965-f9d86300-d19d-11ea-9cc4-d785a63aad97.png)

I was wondering if it was somehow possible to check if someone is attuned to this item and have the same thing done as with Jack of All Trades. This might be too specific though, and if it is not possible no worries 😅.

**Comment by kakaroto** [comment]
That's a good question. It's specific yes, and if I add it, it wouldn't be for that magic item but rather as a way to add modifiers to ability checks in general. The problem is that the abilities listed in D&D Beyond are just your raw abilities, it can't show magical bonuses there because the modifier shouldn't affect things like weapon damage (which uses the same modifier). So really the problem here is that D&D Beyond doesn't have a "ability checks" section, like it has for saving throws. This only applies when it comes to having magical bonuses of course, so rolling from the ability list has made sense so far.
Will have to think on how to allow this, maybe a custom modifier field in the setttings just for ability check magical bonuses or something.
