### ISSUE TITLE
Add an option to enable Divine Fury 

### ISSUE THREAD

**Issue by tony--** [kakaroto/Beyond20#493]
<img width="242" alt="Screen Shot 2020-08-17 at 9 47 11 PM" src="https://user-images.githubusercontent.com/513830/90471682-b48bbf00-e0d3-11ea-921e-3aee255d4b76.png">

Rage is enabled, character has the divine fury feature and is dual wielding.

Two problems shown with the second attack in the above screenshot:
Expected: Divine Fury only applies to the first attack that hits.
Actual: Divine Fury applies to each attack that hits.
~~Expected: Divine Fury damage is not affected by crits.~~
~~Actual: Divine Fury is modified by crit.~~

**Comment by kakaroto** [comment]
Hi, thanks for the report.
The first one : apply to the first attack only is known (though I can't find an issue about it, so it's good you filed this one, otherwise, it would have been forgotten!). Originally, it was thought to always apply when raging so it was tied to it, but since it's only on the first attack, I think a new option is needed, like with Sneak Attack.
I know this was discussed on Discord, so I'm not sure if it was decided "the user can ignore it for that second roll, since they should know the rules and they wouldn't bother to disable it manually then enable it for each attack", or if it was "this needs to be added to the same level as sneak attack".

For the second issue, I disagree, I don't see anywhere anything that says Divine Fury shouldn't be affected by crits. As per the rules, crits double all your damage dice. Divine Fury is damage, and has dice, so those get doubled. The same rule (again) applies for Sneak Attack.
If you have any specific (and official) text that says that Divine Fury itself is for some reason excluded from crits, then please share, otherwise, I consider it not to be valid.

**Comment by tony--** [comment]
I stand corrected!  Only one issue with Divine Fury 😄

**Comment by tony--** [comment]
I forgot to mention, thank you for the quick reply!

**Comment by kakaroto** [comment]
no problem ;) And now you can tell your DM to count those divine fury crits :p
