### ISSUE TITLE
Monk Monastic Tradition - Chosen tradition not shared

### ISSUE THREAD

**Issue by thelontx** [kakaroto/Beyond20#506]
In DnD Beyond, the Monk gets a Monastic Tradition at 3rd Level.   In DnD Beyond, the general description is shown in the sidebar in addition to the specific Tradition chosen by the character.   e.g. Way of the Four Elements.

When the Beyond20 button is pressed, only the general description shows in the Roll20 chat.  The specific Tradition chosen by the Monk is not included.   

This is a minor issue.  When the general description is read in Roll20 quickly, it includes the tradition of "Way of the Open Hand".  This could be confusing if someone reads quickly and does not catch this is a general description.

**Comment by kakaroto** [comment]
Beyond20 will only send what appears in D&D Beyond. It has no knowledge of any of the rules or anything like that, so if the full description is not shown, that would be a D&D Beyond issue.

This is what I get in D&D Beyond. There is no description anywhere to use.
![image](https://user-images.githubusercontent.com/27990/92663874-86fbf500-f2d0-11ea-9271-67769756a8f8.png)

**Comment by kakaroto** [comment]
I think I know what you meant (just after posting). Not that it should display the description of "way of the open hand" but rather print that line from the description which says "way of the open hand".
Turns out that line is not actually part of the description "content" but is in a separate section called "extra", but it should be possible to take that into account and display it as well.
Re-opening.
