### ISSUE TITLE
Savage Attacks & Legendary Criticals

### ISSUE THREAD

**Issue by voidblack** [kakaroto/Beyond20#52]
Amazing work - thank you for putting this out there!

I noticed in testing out this plug in that you refer to "Brutal Critical and Save Attacks" in both the feature list on the website and on the in-app settings toggle. I think you intended it to say "Brutal Critical and Savage Attacks". Further more, savage attacks do not appear to be working for me with a half orc using any of the three weapons I tried (Longsword, Greatsword, Yklwa). The crit damage rolled is only the standard crit damage. I can DM you the sheet link if you find that useful.

Lastly, I notice the improved critical could not be turned on for Oath of Heroism Paladins using the Legendary Criticals class feature, but as this is a UA class still, probably not worth adding to the core app yet. 

Thanks again for all your work and I hope you find this feedback useful!

**Comment by kakaroto** [comment]
Thank you for the report! Yes, it's definitely a typo and I will fix it right away!

For the savage attacks not working for you, I did find a bug and thanks for finding it, but first, just to be extra sure:
Did you make sure you selected the class & features tab at least once since you've had the ability ? https://beyond20.here-for-more.info/faq#can-beyond20-do-insert-specific-feature
Since you talk about the typo in the settings toggle, my guess is that you did, so there is 1 more thing to be aware of: it only does the brutal critical on melee attacks, not ranged attacks.

Finally, yes, I've done some tests, and I can confirm that there is a bug for both the brutal critical and savage attacks on Roll20 where if the weapon does only one damage (no two-handed, no rage damage, no secondary fire damage, no sneak attack or whatever), then the brutal is not rolled in Roll20 (though it is sent properly from the D&D Beyond side of things).
I'm guessing if it doesn't see a second damage, it ignores the second critical damage as well.

**Comment by voidblack** [comment]
1.) Class and features tab: Yes
2.) Melee Attacks: I only tried melee attacks
3.) I was able to replicate just that. For a versital attack with both one handed and two handed damage being rolled, the additional crit damage is rolled, but only for the two handed damage. Looking at how it was sent, it seems you are treating savage/brutal as a separate additional crit. Instead of adding another set of rolls for the abilities, perhaps just changing the crit roll dice directly would avoid this issue. Roll20 does just that, which makes me think its possible,

Example:
On a long sword being wielded in two hands by a 16 str half orc, 1d10+3 damage is rolled and an additional 2d10 for crits. For our example, lets assign the damage rolled is (1)+3 with a crit value of 8 and an additional savage value of 1.
Instead of sending a packet resulting in: 4+Crit: 8 | 1
Send the packet resulting in: 4+Crit: 9

Do you think this is a feasible solution?

**Comment by kakaroto** [comment]
It's just a bug in my implementation of the roll20 damage to properties function. It sets 'dmg1' and 'crit1' to the first damage and first crit, then sets 'dmg2' and 'crit2' to the rest of the damages. The problem is that it only does it if there is more 1 damage. I've fixed it by just handling the case of `crit_damages.length > 1 && damages.length == 1`
