### ISSUE TITLE
Doesn't show up with Simple World Building 

### ISSUE THREAD

**Issue by ervwalter** [kakaroto/Beyond20#557]
**Describe the bug**
With Foundry 0.6.6, this module does not show up for simple world building worlds.  My impression is that this is not what you intend.

**To Reproduce**
1. Install the module
2. Create a simple world building world
3. Go do module configuration in the world
4. The module does not appear as an option to enable

**Expected behavior**
It would show up for simple world building worlds.

**Screenshots**

**Additional context**
I don't know if an update to FVTT was why this started mattering (i.e. maybe a recent version started enforcing the system list in the module.json).  This appears to be the cause and adding "worldbuilding" to the list makes it work:

https://github.com/kakaroto/Beyond20/blob/master/FVTT-module/beyond20/module.json#L7

**Comment by kakaroto** [comment]
I'm not sure I want to go further in this. D&D Beyond is very specific to D&D 5e, and I understand that some people might be using SWS instead of dnd5e for the system, and was ok with adding `health` instead of `hp` for the HP syncing, but the module is about to change and do native Foundry calls and will become very specific to the dnd5e data format, so it wouldn't make sense for it to support sws as well.

I'm quite unsure for why I'd want to support both systems when D&D Beyond is meant for D&D 5e. Convince me I'm wrong and I'll consider the question further.

Thanks

**Comment by ervwalter** [comment]
Your code, so your decision, of course.  Close this as you see fit.

**Comment by kakaroto** [comment]
Alright, thanks! 👍
