### ISSUE TITLE
Versatile weapon damage for monsters displays incorrectly

### ISSUE THREAD

**Issue by mark-drury** [kakaroto/Beyond20#569]
First post...

I ran a Helmed Horror last night as part of an Eberron campaign and the versatile weapon didn't work correctly in beyond20 with foundryVTT version 0.6.6

The 1 and 2 handed weapon damage display correctly (although they are simply called slashing damage) 

The problem is the system adds both the slashing damage numbers together and displays the result which is problematic.

![Screen Shot 2020-10-22 at 10 10 43 AM](https://user-images.githubusercontent.com/25595383/96900056-e829f300-144e-11eb-9248-554e6d3b08a9.png)

**Comment by kakaroto** [comment]
Hi.
There is no concept of versatile for NPCs, only for character sheets. 
The monster statblock is parsed and it will roll the damages listed there, it's up to you as a player/GM to understand the output and decide what counts and what doesn't.
Look at the druid for example which has descriptions about whether or not shillelagh spell applies or not. I won't be adding artificial intelligence in order to understand whether a damage is conditional or not based on the english text of the description, so unfortunately this won't fix.
Thanks!
