### ISSUE TITLE
[Optional Rule] Proficiency Dice

### ISSUE THREAD

**Issue by TheKrush** [kakaroto/Beyond20#578]
**Is your feature request related to a problem? Please describe.**
https://www.dndbeyond.com/sources/dmg/dungeon-masters-workshop#ProficiencyDice

**Describe the solution you'd like**
Option to toggle on (preferably per character) to turn on Proficiency dice usage for rolls.

**Describe alternatives you've considered**
I've tried using the custom formula stuff so Roll20 can prompt for proficiency roll and that works for everything except the spell save DC. It should be easy to add by just checking the current proficiency bonus and subtracting it then adding the appropriate proficiency die.

**Additional context**

**Comment by Aeristoka** [comment]
This is not easy in fact, since in most cases (but not all) DnDBeyond is adding the Proficiency bonus, but in a fair few cases, Beyond20 is doing very specific actions in code to add proficiency bonus where it should be for specific feats and such.

Feel free to fork the GitHub and code this up though, then submit a PR.

**Comment by TheKrush** [comment]
I'll give it a shot.

**Comment by Aeristoka** [comment]
> I'll give it a shot.

I'd say maybe also go suggest it as a feature to DnDBeyond themselves. It's something that would be much easier for Beyond20 just to parse, rather than fully implement.

**Comment by kakaroto** [comment]
I agree with @Aeristoka here. Implementing this in Beyond20 would be extremely complex, as it would make Beyond20 into a "knower of rules" as opposed to a simple "passive parser of html content". At the moment, Beyond20 doesn't know anything about D&D rules (other than the special features to add things like sneak attack), so it has no idea if you need to add dexterity or strength to an attack, it has no idea if proficiency is added in the to hit or the damage, or both, it doesn't know anything, because those rules are complex and D&D Beyond already handles all of that for us (off hand weapon doesn't get the dexterity bonus, based on your class, or Feats, you can use str or dex, based on the weapon too, some class features allow you to add proficiency to damage too, etc... D&D rules can get really complicated).

D&D Beyond itself doesn't support the Proficiency Dice, therefore Beyond20 doesn't support it. This needs to be a suggestion to D&D Beyond for them to add support for it, and then Beyond20 would automatically benefit from it.

Sorry about this, but please ignore Aeristoka's suggestion of doing it as a PR, I wouldn't want to merge it because of the complexity involved and changing the fundamental nature of the extension + the huge amount of support/issues that would need to be handled long term if it started to support that.
