### ISSUE TITLE
Add a Beyond20 specific syntax for custom modifiers to do a query

### ISSUE THREAD

**Issue by TheKrush** [kakaroto/Beyond20#579]
**Describe the bug**
If you enter a custom macro like `[[?{Proficiency?|Yes,-4+1d8f|No,+0}]]` for example and have dndbeyond dice rolling turned on it doesn't cause the roll20 prompt to come up.

**To Reproduce**
1. Create a custom formula that would result in a prompt on roll20 (eg. `[[?{Proficiency?|Yes,-4+1d8f|No,+0}]]`)
2. Turn on dndbeyond dice rolling.
3. Roll any check that would use the custom formula.
4. Observe no prompt on roll20

**Expected behavior**
It should prompt on roll20 (or on dndbeyond) regardless of the dice rolling option on dndbeyond.

**Screenshots**

**Browser Info (please complete the following information):**
- Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Additional context**

**Comment by kakaroto** [comment]
That's the expected behavior, that formula is a Roll20 specific macro, it is not a supported format in D&D Beyond so it's not being picked up. If you enter `1d8` for example, that will work, but that formula is Roll20 specific and will work only when you do your rolls in Roll20. When using the Digital Dice, you do the rolls in D&D Beyond, so it doesn't work.
I know this is your solution to the #578 issue, and I'm sorry to shut you down once more, but I don't see any good solution for making it work short of adding support for roll20 macro style support in the Beyond20 roll renderer and I'm not too keen on doing that because that's worst syntax in the world.

**Comment by TheKrush** [comment]
Yeah I can ask dndbeyond about it, and given they are supposed to be creating the _official_ d&d site and that is an official optional rule, it's odd they didn't do it.

**Comment by kakaroto** [comment]
I think this issue can finally be closed thanks to the addition of custom hotkeys which would let you define a custom modifier so you can decide if you want to use the modifier or not with the press of a button instead of a prompt.

![image](https://user-images.githubusercontent.com/27990/132811058-6275a7d2-5d1a-4fa7-ac76-c31efbf5ffc5.png)

Will be available in the upcoming 2.5 release.
