### ISSUE TITLE
Support for Shard Tabletop?

### ISSUE THREAD

**Issue by HeavenForbid** [kakaroto/Beyond20#590]
**Is your feature request related to a problem? Please describe.**
No it is not.

**Describe the solution you'd like**
Shard Tabletop is a relatively new VTT project which is still currently in active development but it is playable and offers many advantages over roll20. I think it may be worth looking into since Beyond20 supports both Roll20 and FoundryVTT.

**Additional context**
Honestly I'm not sure if there's any helpful info I can provide here but the link to their website is - https://play.shardtabletop.com

**Comment by Aeristoka** [comment]
> **Is your feature request related to a problem? Please describe.**
> No it is not.
> 
> **Describe the solution you'd like**
> Shard Tabletop is a relatively new VTT project which is still currently in active development but it is playable and offers many advantages over roll20. I think it may be worth looking into since Beyond20 supports both Roll20 and FoundryVTT.
> 
> **Additional context**
> Honestly I'm not sure if there's any helpful info I can provide here but the link to their website is - https://play.shardtabletop.com

There is no interest from KaKaRoTo in adding support for any new TableTops at this time.

You're welcome to code it up and submit a Pull Request however.

**Comment by kakaroto** [comment]
> You're welcome to code it up and submit a Pull Request however.

Actually, I have recently revised my previous statement about accepting Pull Requests for adding support for new tabletops.
I'll only accept it for well established VTTs, because in the recent year there's been practically 1 new VTT being announced per week, there are too many that are very niche and adding support for one adds a large load of support and long term maintenance as well as complexity to the existing code that I'm not ready to maintain.

Therefore sorry, but if the VTT becomes popular, we can re-evaluate, but until then, it's going to be a no unfortunately.

**Comment by Aeristoka** [comment]
> > You're welcome to code it up and submit a Pull Request however.
> 
> Actually, I have recently revised my previous statement about accepting Pull Requests for adding support for new tabletops.
> I'll only accept it for well established VTTs, because in the recent year there's been practically 1 new VTT being announced per week, there are too many that are very niche and adding support for one adds a large load of support and long term maintenance as well as complexity to the existing code that I'm not ready to maintain.
> 
> Therefore sorry, but if the VTT becomes popular, we can re-evaluate, but until then, it's going to be a no unfortunately.

I am 100% onboard with this decision.
