### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by MattGill98** [kakaroto/Beyond20#597]
I use Safari as my daily driver, but have to use Firefox or Chrome to use this extension with Roll20 and D&D Beyond. The extension is so good that I make this tradeoff, but ideally there would be a Safari extension that would allow me to use the features like force touch etc.

**Describe the solution you'd like**
A safari compatible version of the plugin.

**Describe alternatives you've considered**
I've tried running `xcrun safari-web-extension-converter --project-location safari chrome` from the `build` directory. I've also tried converting the firefox extension. On each the extension mostly works, except it will always give the `No VTT found that matches your settings.` error.

**Additional context**
I've tried adding a switch in the `getBrowser()` function to return Safari when it's correct and prevent the cloneInto() function being run (which won't be recognised in Safari). From here there seem to be no JS errors, but I still get the same `No VTT` message. My knowledge of writing extensions is slim to none, but I see that the Octotree source makes very minimal changes to get their Safari extension, and Safari supports the 'chrome' namespace, so I can't imagine it would be too much effort?

If you can provide pointers or tips I'm more than happy to try again so I can maybe make a contribution.

PS. Absolutely love this project, great work!

**Comment by Aeristoka** [comment]
I'll let @kakaroto comment, but it's very unlikely to happen honestly.

**Comment by kakaroto** [comment]
Yeah, this wouldn't happen unfortunately because I don't use Safari and it's not chromium based so it would require additional work to get it working. Even Microsoft have contacted me asking to add the extension to the Edge store (zero changes required) and I'm hesitating because of the extra overhead in submitting the package to yet another site upon release.
Getting it to work with Safari would be a headache in itself that I don't think I'll ever be ready for. Sorry!

**Comment by cpekruhn** [comment]
This is disappointing, but I get it. The latest Safari build supposedly makes it easy to [port Chrome extensions](https://techcrunch.com/2020/06/25/apple-will-let-you-port-google-chrome-extensions-to-safari/) to work in Safari. That said, I have not heard how that has worked from other developers. But if you aren't familiar with Xcode or Apple development, I totally understand.

**Comment by kakaroto** [comment]
I've seen Xcode once before, yeah, I'm not familiar with it and not keen on getting familiar with it either :) I'm gonna assume I'd need a mac to even use it.

**Comment by joshnroy** [comment]
Hi All,

@kakaroto If I investigated this in my spare time and got it to work, is Safari support something you're interested in integrating to the project or not at all?

I'm not too familiar with xcode/safari extensions, but I just got a Mac M1 and am interested in trying to port this extension to Safari (ideally, there would be a way I can set it up to auto-build from chrome extension to safari extension or something).

Also +1 to loving this project! Have been using it weekly for the past couple years for zoom DnD and it has made the pandemic way more managable! Thanks for all your work on it!

**Comment by kakaroto** [comment]
Hey @joshnroy,
Thanks for the suggestion and willingness to help, but while I appreciate the sentiment, I don't think that changes the situation unfortunately.
As I mentioned before, I'm not adding it to Edge either (even if Microsoft keeps pestering me about it) just to avoid the additional step of releasing on yet another platform every time I make an update. 

The issue with safari support is that if I can't handle it myself then it would add a dependency on you (i.e contacting you to build it, waiting/delaying a release if you're not immediately available, making sure the last build is tested on safari to see if it works as expected or if it broke, etc..) and that's not something I can afford to do.
Also, FVTT doesn't work on Safari because Apple never updated it to support newer web standards, and I'm already annoyed at Firefox for not supporting manifest v3, I don't want to think of the implications of safari support, hehe.

Thanks again for volunteering to help!

**Comment by joshnroy** [comment]
Ah ok, that makes sense. Thanks for the quick response and explanation!

**Comment by Aeristoka** [comment]
> Hey @joshnroy, Thanks for the suggestion and willingness to help, but while I appreciate the sentiment, I don't think that changes the situation unfortunately. As I mentioned before, I'm not adding it to Edge either (even if Microsoft keeps pestering me about it) just to avoid the additional step of releasing on yet another platform every time I make an update.
> 
> The issue with safari support is that if I can't handle it myself then it would add a dependency on you (i.e contacting you to build it, waiting/delaying a release if you're not immediately available, making sure the last build is tested on safari to see if it works as expected or if it broke, etc..) and that's not something I can afford to do. Also, FVTT doesn't work on Safari because Apple never updated it to support newer web standards, and I'm already annoyed at Firefox for not supporting manifest v3, I don't want to think of the implications of safari support, hehe.
> 
> Thanks again for volunteering to help!

The funniest part about the Edge store is Edge is literally Chromium, so you can just install from the Chrome store (which is 107% not what Microsoft wants, but you can do it :D )

**Comment by MattGill98** [comment]
@joshnroy sounds awesome that you've got something working! Would you be happy to push your changes to a fork or gist? I'd love to learn from the steps you took to hopefully reproduce the same for myself

**Comment by joshnroy** [comment]
Oh, I don't have it working. Sorry @MattGill98 - wanted to ask the author before doing so

**Comment by MattGill98** [comment]
My bad sorry, if I'd have read the 'if' correctly I'd have known that! 😅
