### ISSUE TITLE
Roll20 vtt chat window not styling results from dndbeyond character sheet correctly

### ISSUE THREAD

**Issue by petermpopp** [kakaroto/Beyond20#611]
I have confirmed that that the campaign on roll20 uses the DnD 5E by Roll20 character sheet template (see screenshot). I have confirmed that beyond20 is using the DnD 5E by Roll20 charactersheet for the Roll20 Character Sheet Setting (see screenshot). I've reinstalled the beyond20 extension in chrome and quit out of my roll20. I've cleared the chat archive and deleted the chat archive, yet the styles have not updated. they were working fine on Wednesday Nov 25th 2020.
![Screen Shot 2020-12-07 at 4 44 07 PM](https://user-images.githubusercontent.com/16158089/101422551-c1fbcd80-38ab-11eb-96b5-d94fa57d03e6.png)
![Screen Shot 2020-12-07 at 4 43 51 PM](https://user-images.githubusercontent.com/16158089/101422552-c2946400-38ab-11eb-95b9-abb20da96c87.png)
![Screen Shot 2020-12-07 at 4 43 11 PM](https://user-images.githubusercontent.com/16158089/101422553-c2946400-38ab-11eb-896d-21c31b910838.png)
![Screen Shot 2020-12-07 at 4 42 25 PM](https://user-images.githubusercontent.com/16158089/101422555-c32cfa80-38ab-11eb-9580-ec4466843d7f.png)

**Comment by DarrynGlass** [comment]
The bug comes from an update on Roll20's side. This is fixed on the developer mode and should be available in the next update. 

Roll20 has made a change to their site yesterday which causes some functionality from Beyond20 to stop working, forcing all rolls to be sent using the default roll template even if your character sheet template is set to D&D 5e.

As a temporary workaround, you can use the development version of Beyond20 which fixes the issue.
For instructions, check out https://github.com/kakaroto/Beyond20#developer-mode-installation

@kakaroto please close
