### ISSUE TITLE
Raging while wild shape

### ISSUE THREAD

**Issue by jakelbarnett** [kakaroto/Beyond20#624]
Hello,

I'm playing a Barbarian 3 / Druid 2. When I toggle the "Barbarian: Rage! You are raging, ARRGGHHHHHH" option, it grants advantage to str checks/saves and +2 dmg for rolls made with the main character, but doesn't apply to any checks/saves/dmg rolls made by my brown bear wildshape.

Thanks for reading this, I greatly appreciate this extension! I've even convinced my players to use it!

**Comment by kakaroto** [comment]
That's kind of a very specific use case, that I don't think Beyond20 would support. There's a limit to how much automation it can do, and there's no difference between "Barbarian / Druid" doing a rage wildshape and a "Barbarian / Ranger" doing a beast companion attack. The extra creatures are considered as extra creatures, not as your own self.
I see that D&D Beyond adds a "Wildshape" feature to the statblock, so that could be used, but I'm wary to trying to do too much.

**Comment by kakaroto** [comment]
Bumping this in priority
