### ISSUE TITLE
Using hotkeys to roll bonus die with adv/disadv causes the bonus die to roll twice, once per d20.

### ISSUE THREAD

**Issue by HaarisQureshi** [kakaroto/Beyond20#642]
As discussed in Discord (https://discord.com/channels/578874022968688640/579077349375475725/790352217688506369)

**Is your feature request related to a problem? Please describe.**
RAW are adv is 2d20k1+1d4, currently if you roll a bonus dice at the time adv with hotkeys (e.g. by having 'shift' as advantage and 'B' as +1d4), it will instead roll 2(1d20+1d4)k1. Same will presumably happen with disadvantage and other bonus dice. 
![image](https://user-images.githubusercontent.com/18645717/103158361-c2093200-47b4-11eb-9e3f-dcc7c02fb901.png)

**Describe the solution you'd like**
The bonus die isn't rolled twice. 

**Describe alternatives you've considered**
The solution I think of is a messy one of having an adv and a disadv option for each and every bonus dice option, but this would make for a bloated UI. Dunno otherwise if changing the way it works when rolling an adv and bonus die, so it doesn't combine them like it does, or making the hotkey toggle on the advantage and then just roll the bonus.

**Comment by kakaroto** [comment]
Thinking on this further, and realizing that it's just not doable on Roll20 because of the way it works. While we do have greater control on Discord/Foundry or if we use the Beyond20 roll renderer (digital dice), I don't like having uneven capabilities, and it still makes for a very complex and convoluted fix for something that really is not worth that effort (and makes the code harder to maintain long term).
At the end of the day, it remains a random roll, which is the important part.
Here's a conclusion I posted in Discord to someone else recently, which I'll use as the conclusion to this issue and close it.
![image](https://user-images.githubusercontent.com/27990/147393752-faace1cc-867a-4121-899a-bf8302a34e3e.png)

Thanks for understanding.
