### ISSUE TITLE
Always roll twice does not work for initative on roll20.

### ISSUE THREAD

**Issue by spdkils** [kakaroto/Beyond20#66]
Weapon of warning gives advantage on init, but it will not roll twice on roll 20. Not sure if that is because how it does the sheet or you.

**Comment by kakaroto** [comment]
Always roll twice can't work if you want to also add to the tracker. If you disable the  option to auto-add to tracker, it will work, but if you enable it, then it will only roll once (because tracker needs one value).
Closing the issue but if you have a better suggestion on how to handle it, you can re-open the issue and let me know.
Thanks!

**Comment by kakaroto** [comment]
I had an idea on how to improve this. Since if you had roll with advantage, it will still going to roll for initiative with advantage (using `2d20kh1` instead of two `1d20` formulas), I decided that if you have 'always roll twice' option selected, it can just query you for whether or not you want to roll with advantage when you do an initiative roll.
Initiative rolls should be 'rare' enough that it won't be a hindrance to have the query for those rolls only when you have it set to roll twice. I hope this solves the issue for you!
