### ISSUE TITLE
Absorb chat damage buttons into companion module

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#663]
Foundry chat damage buttons for beyond20 module is unmaintained (8 months since last commit) and might get dropped from the list of modules : https://gitlab.com/Ionshard/foundry-vtt-chatdamagebuttons-beyond20

`@Calego` suggested we absorb it into the Beyond20 companion module as an optional setting. 
Module seems small enough and adds good functionality.

**Comment by Aeristoka** [comment]
I'm incredibly supportive of this.

**Comment by cgplayer2000** [comment]
As am I.  I used to use that module quite a bit, but I dropped it, given that it has not been updated.  Those buttons did speed things up a bit.

**Comment by Aeristoka** [comment]
> As am I. I used to use that module quite a bit, but I dropped it, given that it has not been updated. Those buttons did speed things up a bit.

It still works perfectly fine even in 0.7.9, so I'd say pick it up again until it's absorbed.

**Comment by kakaroto** [comment]
yeah, it works fine, so no reason to drop it.

**Comment by cgplayer2000** [comment]
Okay, thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Aeristoka** [comment]
I'll suggest changing the application buttons to be more like the ones used in MidiQOL now as in screenshot:
![image](https://user-images.githubusercontent.com/7988297/110217131-aa62bf80-7e6f-11eb-9f51-4569579b376b.png)

Makes it super clear what each thing is, instead of having to look at little icons and try to remember.
