### ISSUE TITLE
Suggestion - Custom Step by Step roller

### ISSUE THREAD

**Issue by GayKiwi** [kakaroto/Beyond20#67]
Just wondering how easy it would be to add a "Custom Roller" so that rolls that aren't supported can be made.

For example, a small window comes up with a group of questions:

_Page 1_
**Choose an Ability Modifier**
No Ability
Strength....
Charisma

_Page 2_
**Choose Proficiency Options**
No Proficiency
Proficiency
Expertise
Custom Value

_Page 3_
Custom dice format modifiers - a use once "Custom Roll dice formula bonus".

Page 3 could also ask if this requires a damage roll, and use a custom dice formula to help roll that as well.

As well as an option to allow for sending this roll to the Turn Order.

The main reason for asking for this is our GM asked for something that isn't standard. Roll Intuitive using Wisdom, and if you are proficient with its saves, add proficiency. Tools also don't let you roll them and could be used there.

**Comment by kakaroto** [comment]
Hey, that's a good question. I think you can achieve most of that already with a custom skill. In the D&D Beyond character sheet, click the gear icon at the bottom of the skills screen : 
![image](https://user-images.githubusercontent.com/27990/70399317-e26f1e80-19f0-11ea-8a05-f6491858c5aa.png)

Then in custom skills, add a new skill. If you don't set an ability for it, when you roll it, it will query you for the ability modifier. It doesn't query for the proficiency, as you can set the proficiency on that custom skill directly (and there's no "unknown proficiency" option, unlike the ability).

For custom damage dice, you can have a custom weapon with this in its description :
```
1d4
1d6
1d8
1d10
1d12
1d20
```
And click on the ones you need to roll them. It's not as practical as a guiding list of prompts, but easier than writing such a system (and where to put that button in the page?) though there is the Roll20-ES that adds a dice roller to Roll20 and there's an equivalent module for FVTT as well, which would make things easier.

In those situations, usually I just do a `/roll` directly because it's so unique and custom that it's not worth having it handled differently. 
Beyond20 adds convenience, if some attack/roll you do often enough, you can create a custom skill, custom spell, custom attack in D&D Beyond to do that roll consistently (such as what is suggested to do for Shadow Blade for example), otherwise, just doing it 'the conventional way' is probably best. If it's unique and not an often used roll, then just rolling dice (in real life) or using the /roll command in Roll20 or FVTT is the fastest way to do things.

I hope this helps!
