### ISSUE TITLE
Manual rolls

### ISSUE THREAD

**Issue by hypergig** [kakaroto/Beyond20#690]
I know it sounds totally weird... but... it would be cool to support manual rolls, as in, rolling with real dice in real life. Hear me out.

My whole group uses beyond 20 but I have two players that prefer physical dice, and I don't fault them for it. There is something satisfying about rolling in real life, especially if you love your dice. It would be nice if they can do that but still be recorded in the chat log as any other digital roll.

So basically, you click the red dice icon like you would if you rolled digitally, but in the VTT screen it tells you what dice to roll and asks you to input the result, then uses those values in the template instead of the generated values. I believe roll20 has a some inquiry `?{}` operator that will ask you to input something. 

Maybe it could just be a switch in the main settings for "roll manually". A shortcut would be dope too (like disadvantage / advantage), for the occasional adhoc dice throw. But that is a nice to have.

Thoughts?

**Comment by Aeristoka** [comment]
I'll defer to @kakaroto to answer completely, but I'm nearly certain this is going to be a no.

I believe he plans to hook these Digital Dice over here, which does a similar thing:
![image](https://user-images.githubusercontent.com/7988297/107892113-425c3180-6ee0-11eb-8ad3-8cba1a20cca5.png)

**Comment by kakaroto** [comment]
Yeah, that's not something that would happen because that can easily open things up for cheating, but also, because it's a rather complicated thing to do.
You should check out grape-juice's "manual rolls" module on Foundry where he's actually using machine learning that recognizes the rolls from dice thrown into a dice tray where you'd have your phone's camera looking at the tray from above. It's not yet ready for prime time but it's a pretty cool concept for those who want to use physical dice.

**Comment by hypergig** [comment]
that does sound cool, I will check it out, thanks!

**Comment by kakaroto** [comment]
Here's his patreon by the way : https://www.patreon.com/foundry_grape_juice
And you'll find more information in his discord server (#material-dice channel) : https://discord.gg/je9ZqVKHxQ
Funnily, you're the second person to mention wanting something like this today, lol.
