### ISSUE TITLE
Error Sending HP Update

### ISSUE THREAD

**Issue by jdenbroeder** [kakaroto/Beyond20#7]
I am getting the following error when doing HP updates in D&D Beyond `VM3245 roll20_script.js:5390 Uncaught TypeError: Cannot read property 'Campaign' of undefined`.

It comes from line 5 of `roll20_script.pyj`, looks like there's no d20 object on window but there is a `window.Campaign.characters`.

**Comment by kakaroto** [comment]
Ah, thanks for the report, it seems that the trick I used for doing that (using this 'd20' API object) is actually part of the VTT ES extension, not part of Roll20 itself. 
Can you install it (from [here](https://chrome.google.com/webstore/detail/vtt-enhancement-suite/fadcomaehamhdhekodcpiglabcjkepff?hl=en-GB)) and confirm it fixes the issue for you  ?
For now, I don't plan on finding an alternative way of doing this without that API, so I'll just update the FAQ to make that a requirement.

**Comment by jdenbroeder** [comment]
I actually built a version using `window.Campaign.characters` instead (without the d20) and it seems to be working so far. That being said that extension looks useful so I'll probably check it out anyway.

**Comment by kakaroto** [comment]
Oh, that's nice! Thanks for finding that. 
So I had a look, and it seems the 'd20' variable has a lot more stuff than just d20.Campaign but in the Roll20 [app.js](https://app.roll20.net/assets/app.js), Roll20 does expose the Campaign with a `window.Campaign = d20.Campaign`.
What VTT ES does is to actually patch that file so it also exposes the `d20` variable because it needs access to more stuff that are hidden internally. In our case, we only need the Campaign object so we're good!
