### ISSUE TITLE
Flat modifier option for Hotkeys

### ISSUE THREAD

**Issue by Tatakai-No-kami** [kakaroto/Beyond20#731]
Under the hotkey options, you have the option for adding bonus dice to a roll with a hotkey. But sometimes you need to add a fixed modifier like with Shield Mastery and Dex saves. It would be cool if you could set up a hotkey that adds a fixed modifier like +2 +3 or +4 for when you need to roll and add a fixed situational bonus.

**Comment by kakaroto** [comment]
Adding a situational dice makes sense, because that needs to be rolled, but fixed values don't make sense, because it will just bloat the interface, have a ton of options that most people won't use and it's to save someone from doing a very simple math in their head.. if the bonus is +1, you roll a 13, then the result is 14. You don't need Beyond20 to do that for you. It's different with dice since you can't just do a quick addition in your head.
So that's a request I'm going to reject unfortunately.
Thanks.
