### ISSUE TITLE
Green Flame Blade/Booming Blade totals

### ISSUE THREAD

**Issue by nathanenns** [kakaroto/Beyond20#784]
Hello,

I was wondering if the "Totals" part of using green flame blade and booming blade could be either removed or as a toggle option.

For green flame blade specifically it is damage done to 2 creatures, so totaling is useless for that cantrip, and booming blade, although it all goes to 1 creature, half of it only happens IF the target moves before your next turn.  So not something that needs totaling there either.

**Comment by kakaroto** [comment]
The totals are just values calculated to make things easier for the lazy player, but it will not apply to many situations, and in that case, the player just needs to ignore the value and do the math themselves.
Other than single-handed vs double-handed, there is no other logic over whether or not to calculate totals, it's just a value that's there if there is more than 1 damage.
I don't think I want to add a special case for booming blade/green-flame because it would open a can of worms of having to take into account many other spells or special abilities that sometimes count and sometimes don't, etc... 
At the end of the day, Beyond20 is a tool to make things easier for the player, rather than automate everything for the player, so I'm ok with that value being incorrect in some cases and it's up to the GM/player to decide whether to use it or not.
