### ISSUE TITLE
Magic missile spell should show total number of darts and possibly other spells could benefit.

### ISSUE THREAD

**Issue by chris-mcc** [kakaroto/Beyond20#793]
**Is your feature request related to a problem? Please describe.**
The magic missile spell has different damage outcomes RAW vs RAI so we can't produce a reliable damage total.

Currently Beyond20 only sends across one dart worth of damage - which means that a GM looking at it needs to do some extra work.

But we can make their lives easier.
 
**Describe the solution you'd like**
I'd like the add-on to pass along the total number of darts so GMs/ players can do a simple result x darts or want to roll more dice and how many.

This also applies to spells like scorching ray and eldritch blast which can be 2+ attacks which have the number of rays / attacks underneath the damage info.

**Describe alternatives you've considered**
Rolling based on RAW alone cos its nice and simple for damage calculating.  Like I mean you could have an option for either way or auto expanding these things (scorching ray etc) but can't let the players be too lazy.

**Additional context**

**Comment by pandanielxd** [comment]
To know the amount of darts for Magic Missile you can just look at the spell level which is parsed and work with that.

Also it does not make much sense to show how many attacks you do for scorching ray or eldritch blast since you roll again for each one.

**Comment by kakaroto** [comment]
I'd say that I likely won't add this, for the simple fact that it would only ever be useful for a game between people who cannot talk to each other... In which case, how are you even playing D&D ?

If you do magic missile, I would expect it to be "I cast magic missile at level 3... **roll**, so that's 5 darts of X damage each" and you move on. The simplicity of it is not worth the amount of work and code complexity that it would add in order to implement it.
