### ISSUE TITLE
Publish your extension to Microsoft Edge Addons website

### ISSUE THREAD

**Issue by nagachaitanyalokam** [kakaroto/Beyond20#796]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by DarrynGlass** [comment]
You can go here and install it in Edge today as a workaround.
https://chrome.google.com/webstore/detail/beyond-20/gnblbpbepfbfmoobegdogkglpbhcjofh

**Comment by kakaroto** [comment]
I have received enough emails from Microsoft Edge team that spammed my personal inbox with requests for me to add Beyond20 to the Edge store. I have explicitly refused to do so and even had to request that I stop being spammed.

@nagachaitanyalokam You are a Microsoft Edge Program Manager, not a user asking for help, or reporting an **actual issue** with the extension, therefore you are continuing to spam me, and waste my time.
![image](https://user-images.githubusercontent.com/27990/119181190-3fbd2b00-ba3f-11eb-8910-6dae7bc4e675.png)
Going around and creating an actual issue on my issue tracker to, once again, spam me, asking to have Beyond20 added to your store is the kind of behavior that I abhor and will likely cause me to never want to add my extension to your store because of it.

Thank you for never contacting me again.
