### ISSUE TITLE
No More 3D Dice in Roll20

### ISSUE THREAD

**Issue by Kadalfer** [kakaroto/Beyond20#802]
A couple of months ago the 3D dice that were an excellent and fun feature of Beyond20 stopped working in Roll20.  This has happened to every member of the group I play with, including the DM.  We have all gone through every setting in both Roll20 and DnDBeyond but none of us has been able to resolve it.  I have uninstalled and reinstalled the Beyond20 extension in both Firefox and Chrome but it remains the same.

Any help/suggestions to correct it?

**Comment by DarrynGlass** [comment]
2D dice in roll 20 is not a function of Beyond20.  It is a setting in Roll20.  From the roll20 settings on the right of the screen
![image](https://user-images.githubusercontent.com/29684482/120388002-30b46380-c2f0-11eb-881c-4346a8e991dd.png)

**Comment by Aeristoka** [comment]
Best Guess, did you change this setting in Roll20 itself to anything else?
![image](https://user-images.githubusercontent.com/7988297/120388757-cd730300-c2e8-11eb-8c8e-3378215f044e.png)

I believe it needs to be set to that, so that Beyond20 can use the proper Roll Templates, so that Roll20 can intercept and make the Dice Roll.

**Comment by Kadalfer** [comment]
Thanks very much for the suggestions.  I tried both of them out but unfortunately nothing has changed.

**Comment by DarrynGlass** [comment]
If you type /r 1d20 in the chat do you see the 3D dice?

**Comment by Kadalfer** [comment]
If I type that in the chat I do see the dice.  Likewise, the entire party can roll dice within Roll20 and we can all see them.  It's  when we click on anything in our DnDBeyond character sheets that the dice don't appear.  Those rolls still show up in the chat, so it's all still playable -- just no 3D dice, which we all agreed is fun.

The D&D Beyond Digital Dice setting is currently toggled off, but toggling it on only makes them appear in DnDBeyond so we can't see each other's dice (we're all playing remotely, of course).

I've clicked on all of the spots on the character sheet that you indicate, as well as many others :) -- still no dice.

**Comment by Kadalfer** [comment]
Well, it looks like my DM managed to find a fix by making a copy of the game in Roll20.  While logged into that version of it everything works the way it's supposed to!

Thanks so much for your efforts in helping to figure out the issue.  Hopefully this thread can help out anyone else who experiences this.

**Comment by kakaroto** [comment]
My guess is probably that the copy uses the OGL sheet template, while the old game didn't. That would also likely cause it since Beyond20 needs to roll the dice internally to do all the calculations it needs :
![image](https://user-images.githubusercontent.com/27990/120412882-5314a400-c325-11eb-824a-252eacf1fc58.png)
Either way.... 🤷‍♂️
