### ISSUE TITLE
Wild Magic roll table does not parse correctly

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#804]
The roll table doesn't seem to find the effects : https://www.dndbeyond.com/classes/sorcerer#WildMagic
It detects `Effect` but it's empty. Can't map the rolls to it for some reason.
I don't see anything different in its html to cause that.

**Comment by tyler-macinnis** [comment]
This is so odd, especially when tables like the Supernatural Regions from TCoE and the Names from XGtE seem to work just fine.

**Comment by Aeristoka** [comment]
> This is so odd, especially when tables like the Supernatural Regions from TCoE and the Names from XGtE seem to work just fine.

Likely just DnDBeyond not maintaining consistent web formatting even amongst their own content.

**Comment by tyler-macinnis** [comment]
I think that's probably what it is too because if you go to the Sorcerer class in the phb [https://www.dndbeyond.com/sources/phb/classes#Sorcerer](https://www.dndbeyond.com/sources/phb/classes#Sorcererl) then it works just fine. The issue seems to only occur when viewed via the classes page. [https://www.dndbeyond.com/classes/sorcerer#WildMagic](https://www.dndbeyond.com/classes/sorcerer#WildMagic)
![Screenshot 2021-06-02 123900](https://user-images.githubusercontent.com/21990225/120518410-8dbb2280-c39f-11eb-9bd3-4c0c8e143fc1.png)
![Screenshot 2021-06-02 130457](https://user-images.githubusercontent.com/21990225/120523055-77af6100-c3a3-11eb-85df-5123f81bf8d2.png)
