### ISSUE TITLE
Unnecessary and disruptive "pop-ups" for changelogs

### ISSUE THREAD

**Issue by betterth** [kakaroto/Beyond20#817]
I appreciate that you are updating your software but I am receiving multiple pop-ups per week. Whenever your extension updates, it spawns a pop-up that obstensibly is a changelog but of course has plenty of sponsorship/money links.

I don't care about your changelog.

I'm sorry! I just don't care. Certainly not multiple times a week. I don't want a pop-up every single time you push a change.

Thank you for the software, please stop spamming with pop-ups. If I want to read your changelog, I'll find it. 

Thank you!

**Comment by pandanielxd** [comment]
options -> more options -> scroll down 
https://i.imgur.com/TnsWsqc.png
its not that tough to disable if you wish to :)

**Comment by kakaroto** [comment]
Hey, @betterth. 
I try to keep Beyond20 releases to once every couple of months, but this week has indeed been pretty chaotic due to unfortunate critical bugs and bad timing with D&D Beyond's own update which broke Beyond20 a day after release which required another one.
As answered by @pandanielxd, those who do not want to see when an update occurred have the option to disable it. It is there because I understand that not everyone cares about the changes.
Thanks!
