### ISSUE TITLE
Hidden formatting is added to description boxes

### ISSUE THREAD

**Issue by Houligan86** [kakaroto/Beyond20#836]
**Describe the bug**
When editing a subclass hidden formatting / text is added to the description box causing extra endines

**To Reproduce**
1. Go into editing a subclass
2. Click Save
3. There is extra stuff in the description box

**Expected behavior**
There is not extra stuff added to the description box

**Screenshots**
View Source of the description box
https://i.imgur.com/QgBarxY.png

Description box with all text selected:
https://i.imgur.com/NHnAJsR.png

**Browser Info (please complete the following information):**
Chrome, version 91

**Comment by kakaroto** [comment]
This seems to be related to #822
Thanks!

**Comment by kakaroto** [comment]
This is fixed but it was a bit complex. The extension adds the alertify library which adds those to any site that loads it, so any page that loads the extension will have that, unfortunately the "tinymce" editor that D&D Beyond uses are within iframes which causes the extension to load for them as well. If I disable loading of iframes, then I would lose the ability to have b20 working when someone embeds a DDB page inside of a journal entry in their VTT for example.
I've found that I could add an exclusion for the homebrew editor of subclasses, but the issue is also popping up in the comment section of any monster page too, and I couldn't find a way to avoid it there.
