### ISSUE TITLE
Madness Effect Dice Formula issue

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#839]
**Describe the bug**
In the line below, the die displays as 1d1 <Dice> 0
A character afflicted with short-term madness is subjected to an effect from the Short-Term Madness table for 1d10 minutes.

**To Reproduce**
1. Go to https://www.dndbeyond.com/sources/dmg/running-the-game#Madness

**Expected behavior**
Should be 1d10

**Screen Capture**
![image](https://user-images.githubusercontent.com/29684482/124040683-f9a6a000-d9ca-11eb-8f3a-e55b0fcbdc8d.png)

**Comment by kakaroto** [comment]
Thanks for the report.
It looks like it's an issue from the D&D Beyond data. As much as I'd like to fix it, this is so specific, that I don't see how I could.
This is what the raw HTML looks like with Beyond20 disabled : 
![image](https://user-images.githubusercontent.com/27990/124711004-8c63a500-decb-11eb-9b7f-0478cdd9c08d.png)

As you can see, it says "for 1d1" and then separately in a different span element, it has `0 minutes` instead of having `for 1d10` and then `minutes` separates.

**Comment by DarrynGlass** [comment]
Yeah that is what I thought it would be honestly, but wanted to report it.  Is there a way to report this to DNDBeyond as a problem on their side?

**Comment by kakaroto** [comment]
> Yeah that is what I thought it would be honestly, but wanted to report it. Is there a way to report this to DNDBeyond as a problem on their side?

Yeah, they have a bug report section in their forums here : https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support
Thanks!
