### ISSUE TITLE
Magic Initiate adds the incorrect modifier when the spell is duplicated (when you already have the same spell from your own class)

### ISSUE THREAD

**Issue by Xinomorph** [kakaroto/Beyond20#858]
I tested it with a homebrew version of the "Magic Initiate" feat that is an exact copy of the official one, but I don't have access to the official one to see if the bugs happens with that one too.

While using the "Magic Initiate" feat, and choosing a class that uses a modifier (for spell casting) that is different from the one your own class uses, when you add a level 1 spell that you already had from your own class, you end up with two versions of the same spell, but each version is cast with a different modifier. That is displayed correctly in the D&D Beyond character sheet, but when combined with the "Add Quick Roll areas" feature of Beyond20 both in Chrome and Firefox, the final result is calculated using the same modifier for both versions of the spell (it uses the modifier from your original version of the spell in both cases).

Example:

I have a level 4 Arcane Trickster Rogue that already had "Ice Knife" of his own, at level 4 I choose the "Magic Intiate (Sorcerer)" feat, and the level 1 spell that I choose is also "Ice Knife". My original "Ice Knife" spell is cast using 1d20+4 to hit, because it uses my Intelligence modifier (2) + my proficiency bonus (2); but my Magic Initiate (Sorcerer) version of the "Ice Knife" spell is cast using 1d20+2 to hit, because it uses my Charisma modifier (0) + my proficiency bonus (2). That is displayed correctly on the D&D Beyond character sheet [as you can see here in this picture.](https://i.imgur.com/qofNtKI.png)

Now, when I cast any of those spells while the "Add Quick Roll areas" option is enabled, both versions of the spell are rolled as 1d20+4. The bug happens when using either the quick "attack + damage" button, or just the "to hit" button. When the "Add Quick Roll areas" button is disabled, it works as intended on the "to hit" button. Everything works fine if the spell is not duplicated, the bug only happens when you already had the same spell.

[Here is a video of the bug in action.](https://i.imgur.com/SBfqPJV.mp4)

**Comment by kakaroto** [comment]
Hi. Thanks for the detailed report, that helped greatly understand what the issue you were having was.
The issue here is that both spells have the same name. The problem is that Beyond20 can only roll based on the information it can parse in the sidebar panel of the spell. When using the "quick roll" area, it will find the spell in the list based on its name, and simulate a click on it for the side panel to appear, then parse the information (then if it rolls dice, that will likely hide the side panel, and it all happens in the blink of an eye so you don't actually see that the side panel opened and closed).
In your case, it will find the first spell and open it. I would recommend you change the spell name. For example, if you customize a spell, D&D Beyond would automatically add a `*` at the end of the name to indicate it's a customized spell. If you did something similar, renaming that spell into "Ice Knife*" that should be enough to make Beyond20 differentiate between the two.
Having beyond20 differentiate on its own between the two would be a lot of effort for very little gain since it's such a rare and specific situation.
I hope that helps.

**Comment by Xinomorph** [comment]
Your solution works perfectly, even if I write the same name, as it adds the `*`, I assume it takes it as a different spell, and it uses the correct modifier this time. I imagined it wasn't worth the fix as it was a very odd and specific situation, but the solution you proposed is simple and works great, thanks!
