### ISSUE TITLE
Quick roll to hit / damage not working - firefox

### ISSUE THREAD

**Issue by MuVono** [kakaroto/Beyond20#871]
The ability to click on the HIT/DC and the Damage quick rolls for attacks does not work.

1. Go to a DND Beyond character sheet in Firefox
2. Hover over a skill check and see quick roll popup
3. Hover over HIT/DC and no quick roll popup

I expect to be able to click on the HIT/DC section of the screen and roll my "To hit" without rolling damage. I expect to see a box surrounding the area designating it as a quick roll.

This is how it looks in BRAVE/GOOGLE (Expected behavior)
![image](https://user-images.githubusercontent.com/10763850/134528998-f265697c-2762-4ec7-9f30-e6454cc7b6ea.png)
 This is how it looks in FIREFOX (Problem child)
![image](https://user-images.githubusercontent.com/10763850/134529142-4384683a-b991-4fb2-b4f6-f226f1cca8e9.png)

- Firefox
 - Version 92
 - ![image](https://user-images.githubusercontent.com/10763850/134528343-76690ca2-df63-4310-9395-89b444724820.png)

This worked months ago, and another update fixed it at one point but the last month or so it hasn't worked as expected. Same character sheet. Same computer. Attempted to uninstall beyond20 and reinstall.

**Comment by kakaroto** [comment]
I don't know what those errors in the console are from, as I haven't seen that before and it doesn't make sense to me either, but your issue looks like it's because you have digital dice disabled on that character sheet. 
Those buttons for to-hit and damage are not added by Beyond20, they are added by D&D Beyond when digital dice rolling is enabled on the character sheet. We simply hook them to roll beyond20 when they are clicked.
Can you confirm?

**Comment by MuVono** [comment]
That is my bad as I thought those were added by Beyond 20. Turning on the digital dice rolling fixed my mistake.
Thanks!

**Comment by kakaroto** [comment]
No worries. Enjoy!
