### ISSUE TITLE
Dread Ambusher Attack Roll Bug

### ISSUE THREAD

**Issue by burck1** [kakaroto/Beyond20#876]
**Describe the bug**
When enabling the "Ranger: Gloom Stalker: Dread Ambusher" setting and rolling an attack, one hit die and two damage dice are rolled all at once. Rather, the dread ambusher feature states "you can make one additional weapon attack" (full description below) so I believe the setting should make two hit dice roles.

**To Reproduce**
1. Setup a level 3 Ranger with the Gloom Stalker archetype
1. Open up the character sheet
1. Click on the Beyond 20 Quick Settings button
1. Enable the "Ranger: Gloom Stalker: Dread Ambusher" setting and click OK
1. Go to Actions
1. Click on Unarmed Strike
1. Click the Beyond 20 attack button
1. See one D20 hit die and two D8 damage dice rolled

**Expected behavior**
Instead of one D20 hit die and two D8 damage dice, the roll should be one D20 hit die and one D8 damage die followed by one more D20 hit die and one more D8 damage die.

**Screenshots**
![image](https://user-images.githubusercontent.com/2439306/135380308-d2598c85-0dec-4993-a600-8efe4e1160b4.png)

**Browser Info (please complete the following information):**
 - Browser: Google Chrome
 - Version: 94.0.4606.61

**Additional context**
- Original commit for adding the Dread Ambusher feature: https://github.com/kakaroto/Beyond20/commit/e0db88e0d39fd33b31278ae2ab4597e5f64ea9f5
- If you have access to XGTE: https://www.dndbeyond.com/sources/xgte/subclasses#DreadAmbusher

> **Dread Ambusher**
> At 3rd level, you master the art of the ambush. You can give yourself a bonus to your initiative rolls equal to your Wisdom modifier.
> At the start of your first turn of each combat, your walking speed increases by 10 feet, which lasts until the end of that turn. If you take the Attack action on that turn, **you can make one additional weapon attack as part of that action. If that attack hits, the target takes an extra 1d8 damage of the weapon’s damage type.**

**Comment by Aeristoka** [comment]
So you would only enable the option for that Extra Attack. There's nothing wrong with how it's implemented.

**Comment by kakaroto** [comment]
I agree with Aeristoka here, this is the correct implementation. The toggle is basically to say "this is a dread ambusher attack".. so you make your normal attack, then you can enable the option and make your second attach, which itself gets an additional 1d8 damage if it hits.
We can't roll two hit dice, because what if you have advantage, or 'disadvantage on your next attack', or what  if you have other class features that add extra damages (say, you're raging too), should those be rolled twice too, etc... So it's really not just about adding a second hit dice to the roll. Each attack has to be done independently for these reasons.

**Comment by burck1** [comment]
You are correct. I definitely misread the mechanic. Thanks for the speedy response!
