### ISSUE TITLE
When using 3D dice in Roll20.net, twice as many damage dice are thrown on the table top

### ISSUE THREAD

**Issue by txmoose** [kakaroto/Beyond20#88]
Both in Chrome and Firefox, when rolling attacks from DnD Beyond, damage dice seem to be thrown twice.  This manifests when using 3D Dice, and only seems to be on the visual.  The dice roll that comes up in the chat is correct, and mousing over it will show the individual numbers that make up the total displayed.  It is just confusing to, for instance, roll an attack with a greatsword, and see 5 dice on the table top: a d20 and 4d6, then see the total in the chat be just 2 of the d6 rolled.

**Comment by kakaroto** [comment]
Hi, thanks for filing this issue. Unfortunately, that's not an issue that is caused by Beyond20 and I have no way of fixing it.

You will notice this exact same behavior with the Roll20 character sheets themselves if you roll any attack from the native character sheet with the damage rolled at the same time as the attack.

![image](https://user-images.githubusercontent.com/27990/72837476-8ab50b80-3c5c-11ea-8b49-9e59715e48f6.png)

The reason for the double dice is that for the attack to be rolled in a single chat message, it needs to roll both the damage and the critical damage dice at the same time *in case* you get a crit. The same thing happens here with Beyond20.

I have tried to make it clear as well in the Beyond20 options that both damage and crits get rolled.
![image](https://user-images.githubusercontent.com/27990/72837693-e41d3a80-3c5c-11ea-90bc-b7a2a886642a.png)

If it is too annoying, then I suggest you either disable the 3D dice, or disable the auto-roll damage & crits options from the 'More options' menu.

I hope that helps,
Thanks.

**Comment by txmoose** [comment]
Hey there, thanks for the quick response.  I guess I just didn't grok that to begin with.  I also didn't really grok that Roll20 had that functionality baked into it.

Appreciate the work you're doing here.  Thanks!
