### ISSUE TITLE
Allow users to change the die that initiative uses

### ISSUE THREAD

**Issue by DuncanMcCain** [kakaroto/Beyond20#887]
Recently, we have been rolling initiative using a d12, rather than a d20, since it more heavily weighs the characters initiative bonus. It is quite frustrating when you take Alert for the +5 initiative bonus and the dwarf goes before you because he rolled a 19 and you rolled a 3.

It would be awesome if, in the beyond20 settings, we were able to change the die that is rolled for initiative. There is not a way to change override this in dndbeyond like you could override the die that a sword uses. I think a good place to put it would be the extension settings. In all honesty, the best place to put it would be in the Roll20 campaign settings, but it's not there and you can't do anything about that. 

I've considered just rolling "/r d12+4" but that doesn't have the bonus of printing that it is the players initiative roll or adding it to their character's Turn tracker.

Thanks!

**Comment by kakaroto** [comment]
That's not something we're willing to do because it's extremely specific to your use case and Beyond20 tries to follow RAW as much as possible (allowing for some customization but this is changing a core rule).
My suggestion would be to simply do an initiative roll, then in roll20's chat box, press the UP arrow, it will display the actual text/command that was sent to chat by Beyond20. Replace the 1d20 in it by a 1d12 and save that as a macro. Then you can just click your macro to roll initiative in the future.
I hope that helps.
