### ISSUE TITLE
No longer linking with astral character sheets

### ISSUE THREAD

**Issue by Cthuwu** [kakaroto/Beyond20#902]
**Describe the bug**
The integration roll buttons are not acting as if the character is rolling it, its just sending the message without linking it to the character.

**To Reproduce**
1. Click and button on Beyond 20 and it wont update info in astral but will send the message.

**Expected behavior**
It should update initiative, health and other stats but is not doing it.

**Comment by kakaroto** [comment]
Astral Tabletop has been abandoned and development has ceased as it reached its end of life. As such, support in Beyond20 is also mostly discontinued as there is no reason to actively continue to work to support a platform that has stopped being developed.
@adriangaro implemented the original support for Astral, if he wishes to look into it and fix it, then that'd be great, but at this time, there is no guarantee that it would continue to function.

**Comment by Aeristoka** [comment]
@adriangaro is this reproducible? (do you care?)

**Comment by adriangaro** [comment]
Sorry for not being able to keep up with support. Work has been taking most my time and haven't used Astral in a good almost 2 years. Can try to reproduce and see what causes it, however I cannot say when that may be. Sorry for the inconvenience in this regard.

Considering they haven't done any updates since it was updated, my bet is either maybe something recently changed in the data sent from beyond to astral which might cause the workflow to fail at some point.

**Comment by Aeristoka** [comment]
Astral is officially dead.
