### ISSUE TITLE
Incorrect Dice Formula in Encounter Builder 

### ISSUE THREAD

**Issue by tbbstny** [kakaroto/Beyond20#917]
As shown in the screenshot, I have several monsters in the encounter.  I will click on each of them in turn to see their stats, the 1st time I do this, all looks good as far as I have been able to determine.  However, on subsequent clicks on the Ocr Hand of Yurtus, the Dice Formula in the _**Spellcasting**_ section changed from `+4 to hit` to `1d8 to hit`.  Just trying it again now, I had to click back and forth between monsters several times before this happened.  So not consistently on the 2nd time in.  

![screenshot](https://user-images.githubusercontent.com/3798081/150261441-459aeab3-780a-4481-bb63-b3fb32a1ade1.png)

**Comment by Aeristoka** [comment]
I managed to recreate it once, but I would bet it's related to this reply: https://github.com/kakaroto/Beyond20/issues/838#issuecomment-883182978

The Digital Dice on the Encounter builder are a wild mess (still).

@kakaroto , any thoughts?

**Comment by kakaroto** [comment]
I just wanted to see if I could recreate and got an even worse result : 
![image](https://user-images.githubusercontent.com/27990/150262631-1c26113d-f25a-4e5b-ade5-a358008798b0.png)

Happens to me as soon as I open the encounter and no matter where I click, nothing works or changes... 😬

**Comment by Aeristoka** [comment]
> I just wanted to see if I could recreate and got an even worse result : ![image](https://user-images.githubusercontent.com/27990/150262631-1c26113d-f25a-4e5b-ade5-a358008798b0.png)
> 
> Happens to me as soon as I open the encounter and no matter where I click, nothing works or changes... 😬

😱 

Just DnDBeyond being a broken mess?

**Comment by kakaroto** [comment]
Ah ignore me, I disabled Beyond20 and still got some weird issues, clicking on a roll opened a `talespire://` link which reminded me I had just installed "Beyond the spire" extension to check it out after it was mentioned in #915! 🤣

**Comment by kakaroto** [comment]
Can definitely confirm the bug, yeah, and it's not happening if B20 is disabled. 
If I go from `Orc` to `Orc Hand of Yurtrus`, it's fine, same if I go from `Orc` to `Orc Eye of Gruumsh`. But if I go from "Eye" to "Hand", I get the "(1d8)" in spellcasting. If I go from "Hand" to "Eye" (after passing through "Orc" to clear things out), I instead see "+4" for Gruumsh's Fury instead of 1d8...
Without B20 : 
![image](https://user-images.githubusercontent.com/27990/150263266-0195651a-9487-46a4-b253-3ac4800ae302.png)
![image](https://user-images.githubusercontent.com/27990/150263273-37da076b-1753-40c5-9673-d2f3d82289e2.png)
With B20 (going Hand->Eye): 
![image](https://user-images.githubusercontent.com/27990/150263310-f6a03cc0-8d72-40ae-9c93-1467804b353d.png)
With B20 (going Eye -> Hand) : 
![image](https://user-images.githubusercontent.com/27990/150263334-a14e65ca-c4d2-4fdc-8751-fe40a4998e35.png)

Thanks for the report @tbbstny, we'll look into it!
