### ISSUE TITLE
Set a Max Width in CSS on the Beyond20 Settings Menu

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#938]
On larger monitors (Ultrawide or 1440p and up 16:9), the Settings menu becomes quite unreadable (stretched far too wide):
![image](https://user-images.githubusercontent.com/7988297/153312994-6d28da16-539f-4ddb-ae9f-e58639746ef8.png)

Vs approximately a 1080p:
![image](https://user-images.githubusercontent.com/7988297/153313050-c96d278a-6ab1-4f69-8dcb-ca3952916d41.png)

And a 720p:
![image](https://user-images.githubusercontent.com/7988297/153313099-0fd9e1dd-c764-4f6d-b8bf-9a3c164785c5.png)

It might be a good idea to constrain it to the max width of the scaling on 720p, just to make things as readable as possible.

**Comment by jjchambl** [comment]
Putting a fix in for this now.

**Comment by Aeristoka** [comment]
Found an unintended side effect of this change:
Roll on DnDBeyond with the change:
![image](https://user-images.githubusercontent.com/7988297/154892321-ac347920-3d05-4da8-8ee2-650e583e0628.png)

Roll on DnDBeyond before the change (proper size):
![image](https://user-images.githubusercontent.com/7988297/154892348-d9713f6e-4f69-4903-953a-e2caf19a8631.png)

This needs a pretty serious revisit.

**Comment by kakaroto** [comment]
I've fixed it differently with 5422d3a64f520ef9c98b363a1fe7e230882efa36. The normal alertify has a max width to 500 pixels, which is why the alerts look nice, but the settings had a size that was set to 80% in code, which was overriding the max-width to become `none` and setting the width to a specific value. I've changed it to be 720px as size with a max of 50% width of the window (for mobile) instead of being hardcoded to 80% of width, which fixes it nicely.
