### ISSUE TITLE
Damage Type Missing From Monster Attacks When Rolling Attack and Damage Separately

### ISSUE THREAD

**Issue by amenokos** [kakaroto/Beyond20#949]
**Describe the bug**
If you make a weapon attack from a monster's stat block (from either the Combat Tracker or Compendium) using the combo button that rolls the attack and damage simultaneously, everything works as designed. If you opt to roll the damage separately, the damage type is not displayed in Roll 20's game log. 

**To Reproduce**
1. Begin a combat encounter and select a monster or load a monster's stat block from DDB's compendium. For this example, I'll use the Drow Elite Warrior. 
2. Click on the combo button that says _(B) SHORTSWORD_, The following is displayed in Roll 20 and lists that part of the damage is piercing and the other is poison:
![Screenshot 2022-02-26 23 01 48](https://user-images.githubusercontent.com/69495414/155867738-4a0e1e55-d3da-45bb-a85e-4ebfb4b83a4d.png)

3. Click the _1d6+4_ button for the piercing damage. The following is displayed in Roll 20 but the damage type is not shown:
![Screenshot 2022-02-26 23 04 22](https://user-images.githubusercontent.com/69495414/155867769-a62a2efe-ed5f-4462-9e52-0e4c986d1e35.png)

4. Click the _3d6_ button for the poison damage. The following is displayed in Roll 20, but the damage type is not shown:
![Screenshot 2022-02-26 23 05 20](https://user-images.githubusercontent.com/69495414/155867787-e0e6a1e8-1451-4977-9769-582aa4876391.png)

**Expected behavior**
Damage types should be displayed whether you use the combo button or roll the damage by itself.

**Browser Info (please complete the following information):**
 - Chrome Version 98.0.4758.107 (Official Build) (64-bit)

**Additional Information**
Some other things I noticed while testing this out:
1. When rolling the combo from the compendium entry for Elite Drow Warrior, the sum of the damage was not displayed:
![Screenshot 2022-02-26 23 09 13](https://user-images.githubusercontent.com/69495414/155867865-f75e1c5e-18dd-4e64-8db0-fc3c67b8cccd.png)

But when rolling the combo from the stat block in the combat tracker, the piercing and poison damage total was calculated.
![Screenshot 2022-02-26 23 10 26](https://user-images.githubusercontent.com/69495414/155867891-638d9710-2a29-4a06-a6d3-789b4abaf43a.png)

Shouldn't these behave the same regardless of where the roll is coming from?

2. When rolling the combo attack/damage, the name of the weapon is **bold**, followed by a space and then the d20 modifier in light gray.
![Screenshot 2022-02-26 23 13 18](https://user-images.githubusercontent.com/69495414/155867924-94225895-431f-406a-8e79-6a948151c32a.png)

If you roll the attack individually, the name of the weapon is still **bold**, but there's no trailing space, and the dice formula is also bold and not light gray. The dice formula also includes that 1d20 was rolled, whereas only the modifier is shown when using the combo button.
![Screenshot 2022-02-26 23 15 16](https://user-images.githubusercontent.com/69495414/155867960-23359992-18be-4453-91cf-96d885bf9c07.png)

**Comment by Aeristoka** [comment]
@kakaroto Is this how this is supposed to work? or an oversight? I'm kind of thinking this is because it just sees "dice formula" in the body, and is agnostic to what KIND (in this case damage) of Dice Roll it is

**Comment by kakaroto** [comment]
Yeah, the roll button is Beyond20's action for rolling that attack, the rest of the dice are completely independent and count as just random dice formulas found in text descriptions. They are interpreted the same as if you click on a dice formula appearing in a source book or in an item's description. 

As for this question : 
> Shouldn't these behave the same regardless of where the roll is coming from?

If Roll20 rolls the dice, then we have very little control over what it displays, but if D&D Beyond rolls the dice, then we can do more fancy stuff like displaying each damage separately or showing a total. The one where it didn't show the total was probably because you didn't have digital dice enabled (or, since it's not from an encounter, D&D Beyond doesn't yet support digital dice in standalone statblock pages).

> If you roll the attack individually, the name of the weapon is still bold, but there's no trailing space, and the dice formula is also bold and not light gray. 

Same thing as explained above, it sees a modifier formula, assumes it applies to a d20 and adds it to the formula and rolls it, though I'm not sure why it shows it as part of the name rather than as part of the modifier since it seems to do that for damage formulas.

**Comment by Aeristoka** [comment]
@kakaroto this should be closed then, right?
