### ISSUE TITLE
Voice Channel Text Chat Integration on Discord

### ISSUE THREAD

**Issue by mercernary76** [kakaroto/Beyond20#958]
With Discord's recent(?) addition of a text chat within voice channels, it would be nice to have the Beyond20 Discord bot send rolls into the chat log on voice channels directly, rather than requiring a separate text channel to be open or flip back and forth between channels during game sessions.

It seems Discord treats voice channels differently, and currently the beyond20 bot doesn't recognize the name of a voice channel as being a channel at all.

**Comment by kakaroto** [comment]
I haven't been able to see this feature of text chat on a voice channel, could it be it's a beta feature ?

**Comment by Aeristoka** [comment]
@mercernary76 to bump @kakaroto 's question again, is the Text Chat in Voice Channel a beta feature?

**Comment by mercernary76** [comment]
it doesn’t appear to be a beta feature. everyone i play DnD with has it.

**Comment by mercernary76** [comment]
<img width="640" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/101873796/161630397-288bdf09-b7a0-49a0-848f-63f20b0beaa6.png">
<img width="640" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/101873796/161630413-a6099b78-1c5e-4c7d-89f1-790806337622.png">

**Comment by Aeristoka** [comment]
https://support.discord.com/hc/en-us/community/posts/4878939035543-Open-text-chat-in-voice-channel

Appears it is still VERY limited:
![image](https://user-images.githubusercontent.com/7988297/161630779-c531b6bb-ad7e-452f-8e9b-6c55f06c83d2.png)

**Comment by mercernary76** [comment]
That’s very interesting. Well, I hope as Discord refines the new feature, the Beyond20 bot begins working with it =]
Nick Mercer

817-739-4925
***@***.***
www.nickmercer.weebly.com

**Comment by kakaroto** [comment]
Interesting indeed! Drove me crazy trying to find where it is 😁 
Will add support for it once it reaches general availability.
Thanks!

**Comment by Aeristoka** [comment]
> Interesting indeed! Drove me crazy trying to find where it is 😁 Will add support for it once it reaches general availability. Thanks!

#LuckyGoogling

**Comment by RDanar** [comment]
It looks like they added this to the genpop now...
https://www.youtube.com/watch?v=IlEAb60EYWU

**Comment by mchangrh** [comment]
## Problem?
I haven't gone too deep into the code but I think the problem is because the bot might be pulling the ID of the underlying text channel in the voice channel.

## Solution
the proper way is to actually [send a message to the audio channel](https://discord.js.org/#/docs/discord.js/stable/class/VoiceChannel?scrollTo=send)

## Implementation (for `/secrets`)
I believe [commands/secret.js#L32-L37](https://github.com/kakaroto/Beyond20-discord/blob/a162cfdc2a52f00393de1829b88210de27266a88/commands/secret.js#L32-L37) prevents it binding to an audio channel. A better option might be to check [Channel.isText()](https://discord.js.org/#/docs/discord.js/stable/class/Channel?scrollTo=isText) as that returns true for voice as well

If you don't mind outside contributors, I can try having a go at a PR

**Comment by kakaroto** [comment]
Thanks for the info, that sounds great!
I did look into it last time when they released it, but the API didn't allow it yet (discord.js wasn't yet updated, or the documentation wasn't updated, or I was looking in entirely the wrong place).
I definitely welcome contributions and would happily review/merge your PR.

Thank you!
