### ISSUE TITLE
Add option to use roll renderer with OGL sheet templates

### ISSUE THREAD

**Issue by flyingitalianman** [kakaroto/Beyond20#971]
**Is your feature request related to a problem? Please describe.**
If a weapon has more than 2 damage sources/types/modes, the visualization in Roll20 is messy (see screenshot).

**Describe the solution you'd like**
If more than 2 numbers need to be shown for damage, I would expect new lines to be created, not everything to be crammed in slot #2.

**Describe alternatives you've considered**

**Additional context**
1. be a rogue (sneak attack), lvl 10 arcane trickster
2. get a flaming rapier (piercing and fire damage)
3. use booming blade (thunder damage x2) and attack

https://i.imgur.com/1ejEyIL.png

This is what is shown in the Roll20 chat when I do an attack with the above weapon (compounded with a crit):
https://i.imgur.com/Rzr7Dhh.png

**Comment by Aeristoka** [comment]
This isn't something that Beyond20 can fix, as this is just how cramped the templates are on Roll20. Unless @kakaroto can think of some clever way to output into multiple template sections.

**Comment by flyingitalianman** [comment]
thank you for replying

wouldn't it be possible to send some damages as a separate roll/attack (say, like different magic missile attacks)

it is possible to have only the damage roll without the attack roll, so it could use that interface, no? (I admit I did not look into the code)

**Comment by Aeristoka** [comment]
The core issue here is: Beyond20 is asking Roll20 to do the roll (with Digital Dice on DnDBeyond disabled), so Roll20 is gonna put things where it will.

With Digital Dice enabled, it slots in slightly differently (I can't recall the exact code portion for that), but it's still an issue of how the template works.

Particularly it's this template:
![image](https://user-images.githubusercontent.com/7988297/163033878-6d89760b-0948-4fc1-a7d9-ac1ab07be5e7.png)

You can change that setting to:
![image](https://user-images.githubusercontent.com/7988297/163033941-fa46cc88-6f1b-4bfb-8a3c-0a53441a4d9e.png)

And that will use a different Roll20 Template that displays information in a less "Pretty" but far more readable format.

**Comment by kakaroto** [comment]
Yeah, the issue is that Roll20 only supports 2 damages, and if there's a crit, it adds it next to it on the same boxes. We **could** display them all on separate lines, which is what we do if you enable the D&D Beyond digital dice, and that's because we make the rolls ourselves (DDB does actually) so we already know the roll results, we know which dice to take in case of advantage/disadvantage, we know if it was a crit or not, etc.. so we just display them all properly, see this for example : 
![image](https://user-images.githubusercontent.com/27990/163037981-27ee18bd-6a44-4791-8c98-33ddf271ec71.png)
With sneak attack + dread ambusher + crit : 
![image](https://user-images.githubusercontent.com/27990/163038097-e4d0615f-ae98-494e-8d10-274ff61fdc39.png)
But if we enable the digital dice, it rolls it like this : 
![image](https://user-images.githubusercontent.com/27990/163038163-e078f692-6242-4f26-bc7a-8512d27167ba.png)

The problem is that when rolling an attack like that, with Roll20, you don't have much control and have to fit within the boxes they give you.. if we sent multiple damage rolls separately like we do in the second screenshot, then in case of a critical hit, Roll20 would only roll the crit for the first damage, not the others, etc...

One thing we **could** do is have the option to use the OGL sheet templates but roll using the Beyond20 roll renderer, so you can get the same effect even without the digital dice enabled.

**Comment by Aeristoka** [comment]
That's actually probably a good idea, it'll clean up a pretty longstanding complaint.

**Comment by flyingitalianman** [comment]
Thank you for looking into this!
And yes, the digital dice option is exactly what I was hoping to get in terms of visualization. I'll use that for the time being.
