### ISSUE TITLE
Magic Staff Melee Options

### ISSUE THREAD

**Issue by patelsp198** [kakaroto/Beyond20#99]
suggestion: add an option to roll a magic staff like a quarterstaff.

**Comment by kakaroto** [comment]
Thanks for the suggestion. Unfortunately, there is no way for me to do that because the magic staff has no attributes for Beyond20 to parse and use. I can only roll what information is on the sidebar.
For example : 
![image](https://user-images.githubusercontent.com/27990/74597485-3ff59c00-502e-11ea-9b5e-253402842739.png)
All I get is a weight and price, no to-hit value, no damage or damage type, no 'light/two-handed/finesse' properties, whether it's melee or ranged, etc... That's all information that Beyond20 doesn't have and the extension doesn't do any math or guesses, and only takes what is offered by D&D Beyond.
My suggestion is to add a quarterstaff to your equipment and rename it to have the same name as the magic staff with `(Melee)` added to the end, for example, so you can use it for actual melee attacks.
